BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  
  XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXX

    
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXX XXXXXX
           XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBB BB BBBB
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Change avatar') X
                XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXX X X X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXX XXXX XXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X X XXXXXXXXXXXX XXXX XXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXX XXXXXX XXXXXX X X XXXXXXX X XXXXX XXXXX X X XXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXX X X XXX X XXX XXX X X X X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXX
      BBBBB
    XXXXXX

    
    XXXX XXXXXXXXXXXXX XXXXXXX XXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
      BBBBB
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
        FFFFFF  gettext(u'tables played') 
      XXXX
      BB BBBBBBBBBBBBBBBB BB BBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX
           XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXX XXXXXXXXX XXX X X XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXX X X X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXX X X X XXXXX XXXXXXXXXXXX XXXX X X X X XXXXXXXXXXXXXXX XXXX X X X XXXX XXXXX XXXXXXXX
           gettext(u'Edit profile') 
        XXXX
      BBBBB
    XXXXXX

  XXXXXX

  
  BB BBBBBBBBBBBB
    XXXXXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Games played') XXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        BBB BBBB BB BBBBBBBBBBBB
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXX XXXXXX
                 XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXX
                  FFFFFFFFF  gettext(u'tables') 
                XXXXXXX
                BB BBBBBBBBBBBBBB B B
                  XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXX X X X X X XXXXXXX X X X X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXX XX XXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXX XXXXX XXXXX X X XXXXXXX XXXXXXX XXXXXXX XXXXX X X XXXXXXX XXXXXX XXXXXXX XXXXX X X XXXXXXX XX XXXXXXXX
                      gettext(u'victories') 
                  XXXXXXX
                BBBBB
              XXXXXX
            XXXXXX
          XXXXXX
        BBBBBB
      XXXXXX
    XXXXXXXXXX
  BBBB
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'No tables played yet.') XXXX
  BBBBB

BBBBBBBB BBBBBBB
