BBBB BBBB

BB BBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
    XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX X X X XXXX X X X X X X XX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXXX gettext(u'Your email is not verified.') XXXXXXXXX
       gettext(u'Verify your email to join tables.') 
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
         XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'CLICK HERE') 
      XXXX
       gettext(u'to receive a new verification email.') 
    XXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX XXX XXXX XXX XXXXXXXX
    XXXXXXXXX
  XXXXXX
BBBBB
