XXXXXXXX
    XXXX XXXXXXXX

    XXXXX XXXXXXXXXXXXX X X
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX X
        XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXX X XXXXX
        X
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
        XX XXXXXX XX XXXXXXXXXX X XX XXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXX XX XXXXXXXXXX XXXXX XXXXX XXX X XXXXXXXXXX XXXXXXXXXXXXXX
        XXX XXXX X XXX
        XXX XXXXXX XXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX X
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXX X XXXXXXXXXXXXXXXXXXXX
                XXXXXX
            X
        X

        XX XXXXXXX X XXXXXX XX XXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
    X

    XXXXX XXXXXXXX XXXXXXXXX X
        XXXXX XXXXX X XXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX

        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX XX XXXXX XXXXXXXX XXXX XXXXXXXXXXX

        XXXXX XXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX

        XX XXXXXXXXX XX X XXXXX XXXXXXXX X XXXXXXXXX XXXXX XXXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX X
            XXXXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX X XXXXXXX
        X

        XXXXX XXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXXXXXXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX X
                XX XXXX XXXXXXX XXX XXXX XX X XXXXX XXXX XXX XXX XXXXXXXXX XXX
                XX XXXXXXX XXX XXXXX XXXX XX XXX XXXXX XXXXXXX XXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXX XX XXXXXXX XXXX XXX XXXXXXXXXXXXXXXX
                XXXXXXX
            X
            XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
    X
XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
