 #
 #
 #
 #
 #
 #

XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
  XXXX X XXXXXX XXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXX X
XXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
  XXXXXXXXX XX X
    XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
      XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXXXXXXXXXXXX X XXXX
      XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXX XXXXXX XXXXX XXXXX XXXXX XXXXX XXXXXX
        XXXXXXXXXX XXXXXXXX XX X
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX
      XXX
      XXX XXXX X XXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
          XX XXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXX X
            XXX XXXX X XXXXXXXXXXXXXXXX
            XX XXXXXX XXXXXXXXXXX X XXXXX
          X
        XXX
      X
    XXX
  XXXXX
XXXXXXXXX
