BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Welcome back') XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Sign in to your account') XXXX
      XXXXXX

      
      XX XXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX
         XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
          XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXX XXX X X X XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXX XXXXXX X XXXXXX XXXXXXXXXXXXXXXX XXX X X XXXXXXXXXXXXXX X X X X X XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXX XXXXXXXX XXX X X X XXXXXXXXXXX X X X X X XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXX XXXXXXX X XXXXX XXX XXXXXX XXXXX X X X X X XXX XXXXXXX XXX X X X XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX
        XXXXXX
         gettext(u'Continue with Google') 
      XXXX


      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
        XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'or') XXXXXXX
        XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXX

      
      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXX XXXXXX
          BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          BBBBBB
        XXXXXX
      BBBBB

      BB BBBB
        XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXX
          BB BBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u"Your account doesn't have access to this page.") XXXX
          BBBB
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Please login to see this page.') XXXX
          BBBBB
        XXXXXX
      BBBBB

      XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBB BBBBBBBBBBBBBBBBXXXXXXBBBBBX XXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX

        
        XXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXX
                 XXXXX
                 XXXXXXXXXXXXXXX
                 XXXXXXXFFFFFFFFFFX
                 XXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXBBBBB XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
        XXXXXX

        
        XXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Forgot password?') XXXX
          XXXXXX
          XXXXXX XXXXXXXXXXXXXXX
                 XXXXX
                 XXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXBBBBB XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
        XXXXXX

        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXX
        XXXXXXXXX
      XXXXXXX

      XX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
         gettext(u"Don't have an account?") 
        XX XXXXXXBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Create one') XXXX
      XXXX

    XXXXXX
  XXXXXX

BBBBBBBB BBBBBBB
