BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXX X X XXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXXXXXX XXXX X X X XXXX XXXXXX XX
          XXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Reset password') XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u"Enter your email and we'll send you a reset link.") XXXX
      XXXXXX

      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXX XXXXXX
          BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          BBBBBB
        XXXXXX
      BBBBB

      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBBBBBB

        XXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXX
                 XXXXX
                 XXXXXXXXXXXX
                 XXXXXXXFFFFFFFFFFX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXBBBBB XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
        XXXXXX

        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
           gettext(u'Send reset link') 
        XXXXXXXXX
      XXXXXXX

      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Back to login') XXXX
        XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
           gettext(u"Don't have an account?") 
          XX XXXXXXBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Create one') XXXX
        XXXX
      XXXXXX

    XXXXXX
  XXXXXX

BBBBBBBB BBBBBBB
