BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXX X X XXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXXXXXX XXXX X X X XXXX XXXXXX XX
          XXXXXX
        XXXXXX
        BB BBBBBBBBBBBBBBB
          XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Set password') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Choose a password for your account.') XXXX
        BBBB
          XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Change password') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Enter your current password and choose a new one.') XXXX
        BBBBB
      XXXXXX

      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBBBBBB

        
        BB BBBBBBBBBBBBBBBBB
        XXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX
                 XXXXX
                 XXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXBBBBB XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
        XXXXXX
        BBBBB

        
        XXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX
                 XXXXX
                 XXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXBBBBB XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
        XXXXXX

        
        XXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX
                 XXXXX
                 XXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXBBBBB XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
        XXXXXX

        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX X X XXXXXXX XXXXXXXX
          BB BBBBBBBBBBBBBBB gettext(u'Set password') BBBB gettext(u'Change password') BBBBB
        XXXXXXXXX
      XXXXXXX

      XX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Back to account') XXXX
      XXXX

    XXXXXX
  XXXXXX

BBBBBBBB BBBBBBB
