BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX

      XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXX XXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXX XXXXXXXXXX XXXX X X XXXXXX XXXXXX XXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXX XX
        XXXXXX
      XXXXXX

      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Check your email') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
         gettext(u"We've sent you instructions to reset your password.") 
      XXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
         gettext(u"If you don't receive an email, check that you entered the address you registered with and look in your spam folder.") 
      XXXX

      XX XXXXXXBBB BBBBBBBX
         XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Back to login') 
      XXXX

    XXXXXX
  XXXXXX

BBBBBBBB BBBBBBB
