BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBB

BBBBB BBBBB
  
BBBBBBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Create your account') XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Join the community and find game tables near you.') XXXX
      XXXXXX

      
      XX XXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX
         XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXXX
          XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXX XXX X X X XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXX XXXXXX X XXXXXX XXXXXXXXXXXXXXXX XXX X X XXXXXXXXXXXXXX X X X X X XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXX XXXXXXXX XXX X X X XXXXXXXXXXX X X X X X XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXX XXXXXXX X XXXXX XXX XXXXXX XXXXX X X X X X XXX XXXXXXX XXX X X X XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX
        XXXXXX
         gettext(u'Signup with Google') 
      XXXX


      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
        XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'or sign up with email') XXXXXXX
        XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXX

      
      
      

      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBBBBBB

        
        XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Access credentials') XXXX

          
          XXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX
                   XXXXX
                   XXXXXXXXXXXX
                   XXXXXXXFFFFFFFFFFX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXX XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXBBBBB XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
          XXXXXX

          
          XXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
                   XXXXX
                   XXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXX XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXBBBBB XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
          XXXXXX

          
          XXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX
                   XXXXX
                   XXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXX XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXBBBBB XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
          XXXXXX
        XXXXXX

        
        XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Your profile') XXXX

          
          XXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX
                   XXXXX
                   XXXXXXXXXXXXXXX
                   XXXXXXXFFFFFFFFFFX
                   XXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXX XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXBBBBB XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Other gamers will call you this way.') XXXX
            BB BBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
          XXXXXX

          
          XXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX
                   XXXXX
                   XXXXXXXXXXXXXX
                   XXXXXXXFFFFFFFFFFX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXX XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXBBBBB XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u"We'll use this to show game tables near you.") XXXX
            BB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
          XXXXXX

          
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
          
          
        XXXXXX
        BB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXFFFFFFF FXXXXBBBBB

        
        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX X X XXXXXXX XXXXXXXX
           gettext(u'Create account') 
        XXXXXXXXX

        XX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
           gettext(u'Already have an account?') 
          XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX

      XXXXXXX
    XXXXXX
  XXXXXX

BBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBB
  
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB
