BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBBB

BBBBB BBBBBBB

  
  XXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'For clubs & associations') XXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX
         gettext(u'Your club deserves') XXXX
         gettext(u'better tools.') 
      XXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXX
         gettext(u'Board-Gamers.com is built by board game enthusiasts, for board game enthusiasts. Free, open source, and always improving.') 
      XXXX
      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        BB BBB BBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBX
           XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXX X X XXXXX X XXXX XXXX X X X XXX XXXXXXXX XXXXXXXXXX XXX X X X XXXXXX XXXXXXXX XXXXXX X X X XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
           gettext(u'Create a free account') 
        XXXX
        BBBBB
        XX XXXXXXBBB BBBBBBBBBBX
           XXXXXXXXXXX XXXXXXXXXXXX XXXXX BB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXBBBBXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXBBBBB XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
           gettext(u'Talk to us')  X
        XXXX
      XXXXXX
    XXXXXX
  XXXXXXXXXX

  
  XXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXX XX XX XXXXXXX XXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXXX XXXXX XXXXX XXXXX X X XXXXXXX XXXXXXXXXXX XXXXX X X X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXXXXXX XXXXX X X X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXX XXXXX XXXXX X X X XXXXXXXXXXXXXXXXX XXXXX X X X XX XXXXXXX X XXXXXXX XXXXX XXXXXXXXXXX XXXXX X X X XXXXX XXXXX XXXXX XXXXX X X X XXXXX XXXXXXXXXXX XXXXX X X X XX XXXX XX
          XXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Free. Forever.') XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
           gettext(u"No subscriptions, no hidden fees, no freemium traps. Board-Gamers.com is and will always be completely free to use. We believe access to great tools shouldn't depend on your budget.") 
        XXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XX
          XXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Open source & community-driven') XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
           gettext(u'The code is open source, maintained by volunteers who love board games. Have a feature request? Your voice matters — the platform evolves based on what clubs actually need.') 
        XXXX





      XXXXXX

    XXXXXX
  XXXXXXXXXX

  
  XXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Our community') XXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Small, but growing fast.') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Real clubs, real players, real game nights.') XXXX
    XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'clubs') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'tables created') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'registered players') XXXX
      XXXXXX
    XXXXXX
  XXXXXXXXXX

  
  XXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Features') XXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Everything your club needs') XXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX

      
      XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXX XX
          XXXXXX
        XXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Game table management') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Create game sessions, set a date, time and maximum players. Members can join with one tap. Perfect for organising evenings at the club.') XXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
             XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
             gettext(u'See example')  X
          XXXX
        XXXXXX
      XXXXXX

      
      XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXXXXXX XXXX X X X XXX XXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXX XXXXX XXXXX X X X XXXXX XXX XX
          XXXXXX
        XXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Member management') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u"Manage your members' registry, track membership validity periods, handle join requests and approvals — all in one place.") XXXX
        XXXXXX
      XXXXXX

      
      XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXX XXXXX XX XXXXX XXXXXXXXXXXX X XXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXX XXXXX XX XXXXX XXXXXXXXXXXXXX XXXXX X X X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X XX XXXXX XX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXX XX
          XXXXXX
        XXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Rankings') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Keep your community engaged with player rankings based on activity. A little friendly competition makes game nights even more fun.') XXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Rankings') XX XBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
                  XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXXXX
             gettext(u'See example')  X
          XXXXXXXXX
        XXXXXX
      XXXXXX

      
      XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXX X XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXX X X XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX X XXXXXXX XXXX XXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX X X X XXXXXXXXX XXXXX XXXXX X X X XXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X X XXXXXXXXX XXXXXX XXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXX XX
          XXXXXX
        XXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Game library') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u"Catalog every game your club owns — or that members bring along. Track who owns what and where it's stored, and export the full list as a CSV anytime.") XXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Game library') XX XBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
                  XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXXXX
             gettext(u'See example')  X
          XXXXXXXXX
        XXXXXX
      XXXXXX

      
      XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XX
          XXXXXX
        XXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Live schedule on your website') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u"Embed upcoming and past game sessions directly on your club's website with a single line of code. Show visitors your association is active and give a preview of what's coming up.") XXXX
          XXXX XXXXXXXXXXX XXXX XXXXXXXXX XXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
               XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXX X
            XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
               XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXX XXXXXXX X
            XXXX
          XXXXXX
        XXXXXX
      XXXXXX

      
      XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Telegram bot') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u"Connect your club's Telegram group to Board-Gamers.com. The bot automatically posts new game sessions, reminds members when a table is almost full, and keeps everyone in sync without leaving the chat.") XXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Telegram bot') XX XBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
                  XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXXXX
             gettext(u'See example')  X
          XXXXXXXXX
        XXXXXX
      XXXXXX

      
      XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX
          XXXXXX
        XXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Physical table calendar') XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u"See all your club's physical tables in a weekly calendar view. Sessions are automatically assigned to available tables based on time slots. Managers can mark tables as reserved for specific groups — keeping planning clear and conflicts to a minimum.") XXXX
        XXXXXX
      XXXXXX

      
      XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXX X X X X X XXXXXXX X X X X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXX XX XXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXX XXXXX XXXXX X X XXXXXXX XXXXXXX XXXXXXX XXXXX X X XXXXXXX XXXXXX XXXXXXX XXXXX X X XXXXXXX XX XX
          XXXXXX
        XXXXXX
        XXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Tournaments') XXXXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Coming soon') XXXXXXX
          XXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Full tournament management is on the roadmap — brackets, standings, rounds. Stay tuned!') XXXX
        XXXXXX
      XXXXXX

    XXXXXX
  XXXXXXXXXX

  
  XXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'Open source') XXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Built in the open, improved together') XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
           gettext(u'You can see every line of code, propose improvements, or even contribute directly. If your club needs a specific feature, send us a message - we build what the community asks for.') 
        XXXX
      XXXXXX





    XXXXXX
  XXXXXXXXXX

  
  BB BBBB
  XXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Frequently asked questions') XXXXX
    XXXXXX

    BBBBBBB BBBB BB BBBBBBBB BB BBBBBBBBBB
    XXXXX
      BBB BBBBB BB BBBBBBBBBB
      XXXX XXXXXXXBB BBB BBBBBBBBBBBBXXXXXBBBBBXX
        BB BBBBBBBBBBBBB
          XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
        BBBBB
        XXXX XXXXXXXXXXXXXXXXXX
          BBB BBB BB BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXX
              XXXXXXXXXXXXX
              XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX X XXXXXXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXX X XX X XXXXXXXXXXXXXXXXX XXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXX
            X
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXX XX
              XXXXXX
            XXXXXXXXX
            XXXX XXXXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXX
              FFFFFFFFFFFFFFF
            XXXXXX
          XXXXXX
          BBBBBB
        XXXXXX
      XXXXXX
      BBBBBB
    XXXXXX
  XXXXXXXXXX
  BBBBB

  
  XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Ready to get started?') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Create your free account in 2 minutes. No credit card, no commitments.') XXXX
      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        BB BBB BBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBX
           XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
           gettext(u'Create a free account')  X
        XXXX
        BBBBB
        XX XXXXXXBBB BBBBBBBBBBX
           XXXXXXXXXXX XXXXXXXXXXXX XXXXX BB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXBBBBXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXBBBBB XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
           gettext(u'Have questions? Talk to us') 
        XXXX
      XXXXXX
    XXXXXX
  XXXXXXXXXX

  
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX XXX XXXX XXX XX
          XXXXXX
        XXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
             XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXX X X X XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX X X X XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXX X X X XXXXXXXXXXXXX XXX X X XXXXXXXXXXXXXXXXXX XXX X X X XXXX XXXXXXXX XXX X X X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X X XXXXX X XXXXXXXX X X X XXX XXX XX
          XXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Preview coming soon') XXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
      XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXX X
        XXXXXXX X XXXXXXX
        XXXXXXX X XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X
      XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX X XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
    X
    XXXXXXXX XXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
      XX XXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXX
  XXXXXXXXX

BBBBBBBB BBBBBBB

BB BBBBBBBBBB
BBBBB BBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFXXXXXXXXX
BBBBBBBB BBBBBB
BBBBB
