BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBB
  XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXXXXX
        XXXXXXX
        XXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXX
        XXXXX XXXXX XX XXXX
        XXXX
          BBB B BB BBBBBB
            XXXX
              XXXXXXX
              XXXXXXX
              XXXFFFFFFFFFFFFFFF XXXXXX
            XXXXX
          BBBBBB
        XXXXX

      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB BBBBBBB
