BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBB

  
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXXXX
      XXXXXX
        XXXXXXXX gettext(u'Hey!') XXXXXXXXX X
         gettext(u'Do you know your way around code and want to contribute to Board-Gamers?') 
        XX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'Contact us') XXXX X
      XXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX XXX XXXX XXX XX
        XXXXXX
      XXXXXXXXX
    XXXXXX
  XXXXXX
  XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
      XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXX X XXXXXXXXXX XX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX XXXX X XXX X XX X XX X XXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
    XXX
  XXXXXXXXX

  
  XXXX XXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBB
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
         gettext(u'Welcome back') X 
      XXXXX
    BBBB
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
         gettext(u'Find your next game night') 
      XXXXX
    BBBBB
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Accept the challenge, join a table!') XXXX

    BB BBB BBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBX
           XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Create a free account') 
        XXXX
        XX XXXXXXBBB BBBBBBBX
           XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXX
        XXXX
      XXXXXX
    BBBBB
  XXXXXX

  
  XXXXXXXX XXXXXXXXXXXXXX

    
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Tables') XXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
           gettext(u'Upcoming') 
        XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Past') 
        XXXXXXXXX
      XXXXXX
    XXXXXX

    
    BB BBB BBBBBBBBBBBBBBBBBBBBB
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Login') XXXX
         gettext(u'to see tables from locations you follow.') 
      XXXX
    BBBB BBBBBBBBBBBBBBBBBBBBBB
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
         gettext(u'Follow new') 
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'locations') XXXX
         gettext(u'to see their open tables here.') 
      XXXX
    BBBB
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
         gettext(u'No open tables from the locations you follow.') 
         gettext(u'Follow new') 
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'locations') XXXX
         gettext(u'to see their tables here.') 
      XXXX
    BBBBB

    
    XXXX XXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXX XXXXXXX
              BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBB
                BBBBBBBBBB BBBBB
              BBBBBB
            XXXXXX
          XXXXXX
        BBBB
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'No open tables right now — why not create one?') XXXX
        BBBBB
      BBBB
        BB BBBBBBBBBBBBB
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXX XXXXXXX
              BBB BBBBB BB BBBBBBBBBBBBB
                BBBBBBBBBB BBBBB
              BBBBBB
            XXXXXX
          XXXXXX
        BBBB
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'No open tables right now — why not create one?') XXXX
        BBBBB
      BBBBB
    XXXXXX

    
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXX XXXXXXX
              BBB BBBBB BB BBBBBBBBBBBBBBBBBBBB
                BBBBBBBBBB BBBBB
              BBBBBB
            XXXXXX
          XXXXXX
        BBBB
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'No past tables from the locations you follow.') XXXX
        BBBBB
      BBBB
        BB BBBBBBBBBBB
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXX XXXXXXX
              BBB BBBBB BB BBBBBBBBBBB
                BBBBBBBBBB BBBBB
              BBBBBB
            XXXXXX
          XXXXXX
        BBBB
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'No past tables yet.') XXXX
        BBBBB
      BBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
         gettext(u'See all tables')  X
      XXXX
    XXXXXX

  XXXXXXXXXX

  
  BB BBBBBBBBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Upcoming events') XXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
           gettext(u'See all events')  X
        XXXX
      XXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        BBB BBBBB BB BBBBBBBBBBBBBBB
          BBBBBBBBBB BBBBB BBBBB
        BBBBBB
      XXXXXX
    XXXXXXXXXX
  BBBBB

  
  BB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXX

      
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Locations') XXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
             gettext(u'List') 
          XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Map') 
          XXXXXXXXX
        XXXXXX
      XXXXXX

      BB BBB BBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
          XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Login') XXXX
           gettext(u'to see near tables.') 
        XXXX
      BBBB BBBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
           gettext(u'Locations near to')  XXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Edit address') XXXX
        XXXX
      BBBB
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Set your address') XXXX
           gettext(u'to see near tables.') 
        XXXX
      BBBBB

      
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
          BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB
            BBBBBBBBBBBBB BBBBBBBB
          BBBBBB
          BBB BBBBBBBB BB BBBBBBBBBBBBBBBB
            BBBBBBBBBBBBB BBBBBBBB
          BBBBBB
        XXXXXX
      XXXXXX

      
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
           gettext(u'See all game clubs')  X
        XXXX
      XXXXXX

      XXXX XXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Have a location to add?') XXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Clubs, associations, game shops are welcome.') XXXX
        XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBX
           XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXX X X X XXXX X X X X X X XX XXX XXXXXXXX  gettext(u'Add location') 
        XXXX
      XXXXXX
    XXXXXXXXXX
  BBBBB

  
  XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'The project') XXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'About Board-Gamers.com') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXX
         gettext(u'Board-Gamers.com is an OPEN and NON-PROFIT project born from the passion of a group of board game enthusiasts.') 
      XXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXX
         gettext(u'Our goal is to make it easier to meet up and play in person, supporting cultural associations and local game shops.') 
      XXXX
      XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
        BB BBB BBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBX
           XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Join free') 
        XXXX
        BBBBB
        XX XXXXXXBBB BBBBBBBX
           XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Discover more')  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XX XXXX XXXXX XXXXXX XXXXX XXXXXXXX
        XXXX
      XXXXXX
    XXXXXX
  XXXXXXXXXX

BBBBBBBB BBBBBBB


BBBBB BBBBBBBBBBB
  XXXXXXXX
    XX XX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXX X
      XXXXX XXXXXXXXXX X XXX XXX XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XX X XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    X XXXXXXXXXX X XXXXXX X XXX

      XXXXX XXXXXXXXX   X XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXX XXXXXXXXXXX X XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXX X XXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     X XXXXXXXXXX X XXXXXXXXXXX X XXXXXXXXXX
    X

    XX XX XXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX X X
      BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBB BBBBBBBBBBBBB
        XXXXXXXX XFFFFFFFFXX XXXXXX X XXXXXX X XXXXXX XBBB BBBBBBBBBBBBBBBBB BBBBBBBBXXX
      BBBBBBBBBBB
      BBB BBB BB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBB BBBBBBBBBBBBB
        XXXXXXXX XFFFFFFFFXX XXXXXX X XXXXXX X XXXXXX XBBB BBBBBBBBBBBBBBBBB BBBBBBBBXXX
      BBBBBBBBBBB
    XX
    XXXXX XXXXXXXXXXXXXX X X gettext(u'View page') XX

    XX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX   X XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXX X
      XXXXX XXXXXX X XXX XXX XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          X XXXXXX X XX X XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXX X XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXXXXXX X XXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  X XXXXXX X XXXXXXXXXXXX X XXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
    X

    XX XX XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX X XXXXXX

    XXXXXXXX XXXXXXXXXXXXX X
      XX XXXX XXX XXXXX X XXXXXX XXX XXXXXXX XX XXXXXX XXXX XXXX XXXXXX XXXXX
    X

    XXXXXXXX XXXXXXXXXXXXXXX X
      XX XXXXXXXXXXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXXXXXXXXX X XXXXX

      XXXXX XXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XX
        XXXXXXX X XXXX XXXXX XXXX XXXX XX
        XXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXX XXXXX
      XXX

      XXXXX XXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXX X XXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX X XXXX XXXXXXXX XXXX XXXXXXX XX
          XXXXXX XXXXXXXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXX X XXXXXXXX X XXXXXX X
            XXX XXXXXXX X XXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X X XXXXXX X
            XXXXXXXX
          XX
          XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXX XXX
        XXX

        XXXXXXXXXXXXXXX XXXX XXXXXXXX XXXX XXXXXXX XXX
        XXXXXXXXXXXXXXXXXXXXXXXX
      XXX

      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXX XXX XXX

      XX XXXXXXXXXXXXXXXXXXXXXX X XX X
        XXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXX XXX XX XXXXXXXXXXXXXXXX
      X
    X
  XXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
BBBBBBBB
