BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX X XXXXXXXXX
  XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXX XXX XXXXXXXX XXXX XXXXXXXXXXX

  BB BBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXFFFFFFFFFFFFFFFFF FFFFFFFXXXX
    XXXXXX

  BBBB
    BB BBBBBBBBBBBBBBBBB
      XX XXXXXXX
         XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX X X XXXXX X XXXXXXXX XX XX XX XXXXXXXX XXXXXXXXXXXX X XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXX XXXXXXXX
      XXXX
    BBBB
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
    BBBBB
  BBBBB
XXXXXX
BBBBBBBB
