BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB
  
  
  XXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXXXXXXX XXXX XXXXXXXXXXX
      XXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXX XXXXXXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXX XXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXXX X XXX XXX XXXX XXXXX X X X XXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    X
  XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Manage') XXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Managers') XXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX

    
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Team') XXXX
      XXXXXX

      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        
        XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXX
          XXXX XXXXXX XXXXXX
               XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
              XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX
            XXXXXX
             gettext(u'Owner') 
          XXXXXXX
        XXXXX

        
        BBB BBBBBBB BB BBBBBBBB
          XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXX
            XXXX XXXXXX XXXXXX
                 XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            BB BBBBBBBB
              XXXXXXX XXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBX
                      XXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX XXX XXXX XXX XX
                XXXXXX
              XXXXXXXXX
            BBBB
              XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Manager') XXXXXXX
            BBBBB
          XXXXX
        BBBBB
          XXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'No managers assigned yet.') XXXXX
        BBBBBB
      XXXXX
    XXXXXX

    
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Add manager') XXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXX XXXXXXX
        BBBBBBBBBB
        XXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XX
          XXXXXX
           gettext(u'Add') 
        XXXXXXXXX
      XXXXXXX
    XXXXXX

    
    BB BBBBBBBB
      XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Transfer ownership') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'You will no longer be the owner of this location.') XXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXXXXXXXXX
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Add me as manager after transfer') XXXXXXX
          XXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX X XXXXXX XXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXX XXXXXXXX XX
            XXXXXX
             gettext(u'Transfer ownership') 
          XXXXXXXXX
        XXXXXXX
      XXXXXX
    BBBBB

  XXXXXX

  
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXX XXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Remove manager?') XXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Are you sure you want to remove')  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
           gettext(u'Cancel') 
        XXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Remove') 
          XXXXXXXXX
        XXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  
  BB BBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXX XXXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Transfer ownership?') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'You will no longer be the owner of this location. This action cannot be undone.') XXXX
        XXXX XXXXXXXXXXX XXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Cancel') 
          XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Transfer') 
          XXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  BBBBB

BBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
  
  XXXXXXXX
    XX XXXXXX XXXXXXX XXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
    XXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXX XXXXXXXXX XXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
  XXXXXXXXX
BBBBBBBB
