BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBB

BBBBB BBBBBBB

  
  XXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Locations') XXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Discover all board game locations near you. Find the perfect place for your next game!') XXXX
  XXXXXX

  
  BB BBBBBBBBBBBBBBBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Your locations') XXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB
          BBBBBBBBBBBBB BBBBBBBB
        BBBBBB
      XXXXXX
    XXXXXXXXXX
  BBBBB

  
  XXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Locations') XXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
           gettext(u'List') 
        XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Map') 
        XXXXXXXXX
      XXXXXX
    XXXXXX

    BB BBB BBBBBBBBBBBBBBBBBBBBB
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Login') XXXX
         gettext(u'to see near tables.') 
      XXXX
    BBBB BBBBBBBBBBBBBBBBBBBBBB
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
         gettext(u'Tables near to')  XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Edit address') XXXX
      XXXX
    BBBB
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Set your address') XXXX
         gettext(u'to see near tables.') 
      XXXX
    BBBBB

    
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        BBB BBBBBBBB BB BBBBBBBBBBBBBBBB
          BBBBBBBBBBBBB BBBBBBBB
        BBBBB
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'No locations available yet.') XXXX
          XXXXXX
        BBBBBB
      XXXXXX
    XXXXXX

    
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXXXXXX

  
  XXXX XXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Have a location to add?') XXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Clubs, associations, game shops are welcome.') XXXX
    XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBX
       XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXX X X X XXXX X X X X X X XX XXX XXXXXXXX
       gettext(u'Add location') 
    XXXX
  XXXXXX

BBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBB
  XXXXXXXX
    XXXXX XXXXXXXXXXXXXX X X
      BBB BBB BB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBB BBBBBBBBBBBBB
        XXXXXXXX XFFFFFFFFXX XXXXXX X XXXXXX X XXXXXX XBBB BBBBBBBBBBBBBBBBB BBBBBBBBXXX
      BBBBBBBBBBB
    XX
    XXXXX XXXXXXXXXXXXXX X X gettext(u'View page') XX

    XXXXX XXXXXXXXXX   X XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXX X
      XXXXX XXXXXX X XXX XXX XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          X XXXXXX X XX X XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXX X XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXXXXXX X XXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  X XXXXXX X XXXXXXXXXXXX X XXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
    X

    XXX XXXXXXXXXXXXXXXXXX X XXXXXX

    XXXXXXXX XXXXXXXXXXXXX XX

    XXXXXXXX XXXXXXXXXXXXXXX X
      XX XXXXXXXXXXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXXXXXXXXX X XXXXX

      XXXXX XXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XX
        XXXXXXX X XXXX XXXXX XXXX XXXX XX
        XXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXX XXXXX
      XXX

      XXXXX XXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXX X XXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX X XXXX XXXXXXXX XXXX XXXXXXX XX
          XXXXXX XXXXXXXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX X
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXX X XXXXXXXX X XXXXXX X
            XXX XXXXXXX X XXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X X XXXXXX X
            XXXXXXXX
          XX
          XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXX XXX
        XXX

        XXXXXXXXXXXXXXX XXXX XXXXXXXX XXXX XXXXXXX XXX
        XXXXXXXXXXXXXXXXXXXXXXXX
      XXX

      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXX XXX XXX

      XX XXXXXXXXXXXXXXXXXXXXXX X XX X
        XXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXX XXX XX XXXXXXXXXXXXXXXX
      X
    X
  XXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
BBBBBBBB
