BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Manage location') XXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Connect a Telegram group to publish open tables.') XXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX

    
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'How to connect a Telegram group') XXXXX
      XXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
        XXX XXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXX gettext(u'Add')  XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX  gettext(u'to your Telegram group as a member.') XXXXXXX
        XXXXX
        XXX XXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
           gettext(u'Generate a token using the button below.') 
        XXXXX
        XXX XXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
           gettext(u'Copy the command and paste it in the Telegram group. The bot will confirm the connection.') 
        XXXXX
        XXX XXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
           gettext(u'Use /tables in the group to see the open tables.') 
        XXXXX
      XXXXX
    XXXXXX

    
    BB BBBBBBB
      XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Connected groups') XXXXX
        XXX XXXXXXXXXXXXXXXXXX
          BBB BBB BB BBBBBBB
            XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXX
              XXXX XXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXX
              XXXXX XXXXXXXXXXX XXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBB
                  XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                BBBBB
              XXXXXXX
              XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Disconnect this group?') XXXX
                BBBBBBBBBB
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                   gettext(u'Disconnect') 
                XXXXXXXXX
              XXXXXXX
            XXXXX
          BBBBBB
        XXXXX
      XXXXXX
    BBBBB

    
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Add a new group') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Generate a one-time token, then paste the command in your Telegram group.') XXXX

      XXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX X X X X X XXX XXX X X X XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X X X X XXXXX XXXXXX XX
        XXXXXX
         gettext(u'Generate token') 
      XXXXXXXXX

      
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXXXX
          X  gettext(u'This token expires in 1 hour and can only be used once.') 
        XXXXXX

        XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Copy and paste this command in your Telegram group:') XXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
               gettext(u'Copy') 
            XXXXXXXXX
          XXXXXX
        XXXXXX

        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
           gettext(u'Make sure the bot') 
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'is already a member of the group before running the command.') 
        XXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX

    
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Available commands') XXXXX
      XXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        XXXX
          XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          X  gettext(u'Connect this group to a location (run once, with a valid token).') 
        XXXXX
        XXXX
          XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          X  gettext(u'Show upcoming open tables for this location.') 
        XXXXX
      XXXXX
    XXXXXX

  XXXXXX

  XXXXXXXX
    XXXXX XXXXXXXXXXXX X XFFFFFFFFXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
      XXXXX XXX X XXXXX
      XXXXXXXXXXXX X XXXXX
      XXXXXXXXXXXXXXX X X gettext(u'Generating…') XX

      XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX X
        XXXXXXX XXXXXXX
        XXXXXXXX X
          XXXXXXXXXXXXXX XXX
          XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XX
      XX
      XXXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXX XX
      XXXXXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX X XXX X XXXXXXXXXXXX X X gettext(u'the bot') XX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XX X gettext(u'Error generating token.') XX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
      XX
      XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Network error. Please try again.') XX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX
      XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXX X XXXXXX
        XXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX X X X X X XXX XXX X X X XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X X X X XXXXX XXXXXX XXXXXXXX  gettext(u'Generate token') XX
      XXX
    XXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
      XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX X X gettext(u'Copied!') XX
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX X XXXXXXXXX XX XXXXXX
      XXX
    X
  XXXXXXXXX

BBBBBBBB BBBBBBB
