BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBB

  
  XX XXXXXXBBB BBBBBBBBBBBBBBBBBX
     XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX X XXXX X XXXXXXXXX XXXXXX XXXXXXXX
     gettext(u'All locations') 
  XXXX

  
  XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
    BB BBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
      XXXXXX
    BBBBB
    XXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBB
        XX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X X X XXX X X X X X X X XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXX XXXXXXXX XXX X X X XX XXX XXXXXXXX
          
          BB BBBBBBBBBBBBBBBBXXXXXXXXXXXXXBBBBB
        XXXX
      BBBBB
    XXXXXX
  XXXXXX

  
  XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX

    
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

      
      BB BBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBB
      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXXXX
        XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Follow')  XXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'See new tables from this location on your homepage.') XXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXX X XXXXXX XXXX X XX X XXXXXXXXX XXXXXX XX
              XXXXXX
               gettext(u'Follow') 
            XXXXXXXXX
          XXXXXXX
        XXXXXX
      XXXXXX
      BBBBB

      
      XXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'About') XXXXX
        BB BBBBBBBBBBBBBBBBBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBB B BBB
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                      XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                      XXXXXXXXXXXXXXX X XXXXXXXX X X gettext(u'Read more') X X X gettext(u'Show less') XX
                    X
                    XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
               gettext(u'Read more') 
            XXXXXXXXX
          BBBB
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
          BBBBB
        BBBBB
        BB BBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXX
          XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
             XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXX X X X XXXXXXXXXXXXXX XXXXXXXX XXXXX X X XXXXXXXXXXXXXXXX XXXXXXXX X XXXXXXXX XXXXXXXXXXXX X XX XXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XX XXX XXXXXXX XXXXX X X X XXXXX XXXXXXXX XXXXXXX XXXXX X X XXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXX X X X XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX X X X XX XXXX XXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX X X X XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX X X X X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
             gettext(u'Website') 
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXX X X X X XXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXXXXX XXXX XXX XXXXXXXXXX XXXXXXX XXXXXXXX
          XXXX
          XXXXXX
        BBBBB
      XXXXXXXXXX

      
      XXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Tables at this location') XXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                 gettext(u'Upcoming') 
              XXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Past') 
              XXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXX XXXXXXX
                BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBB
              XXXXXX
            XXXXXX
          BBBB
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'No upcoming tables — why not create one?') XXXX
          BBBBB
        XXXXXX

        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXX XXXXXXX
                BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBB
              XXXXXX
            XXXXXX
          BBBB
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'No past tables.') XXXX
          BBBBB
        XXXXXX
      XXXXXXXXXX

      
      BB BBBBBBBBBBBBBBBB
        XXXXXXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Events we take part in') XXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBB BBBBBBBBBBB
          XXXXXX
        XXXXXXXXXX
      BBBBB

      
      XXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXX X X X X X XXXXXXX X X X X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXX XX XXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXX XXXXX XXXXX X X XXXXXXX XXXXXXX XXXXXXX XXXXX X X XXXXXXX XXXXXX XXXXXXX XXXXX X X XXXXXXX XX XXXXXXXX
           gettext(u'Most played games') 
        XXXXX
        BB BBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXX
            BBB BBBB BB BBBBBBBBBBBBB
              XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXX
                  XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFXXXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'tables') XXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                         XXXXXXXXXXXXXBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBXXXXXXXXX
                  XXXXXX
                  BB BBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXX XXXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXX X X X X X XXXXXXX X X X X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXX XX XXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXX XXXXX XXXXX X X XXXXXXX XXXXXXX XXXXXXX XXXXX X X XXXXXXX XXXXXX XXXXXXX XXXXX X X XXXXXXX XX XXXXXXXX
                      FFFFFFF F
                    XXXX
                  BBBBB
                XXXXXX
              XXXXXX
            BBBBBB
          XXXXXX
        BBBB
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'No games played at this location.') XXXX
        BBBBB
      XXXXXXXXXX

      
      XXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXX XXXXX XX XXXXX XXXXXXXXXXXX X XXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXX XXXXX XX XXXXX XXXXXXXXXXXXXX XXXXX X X X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X XX XXXXX XX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
           gettext(u'Stats') 
        XXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX X X X XXXXXXXXX XXXXX XXXXX X X X XXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXXXXX XXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXX XXXXXXXX
            XXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX gettext(u'Total gamers') XXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXX
            XXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX gettext(u'Total tables') XXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXX

      
      XXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXX X X X X X XXXXXXX X X X X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXX XX XXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXX XXXXX XXXXX X X XXXXXXX XXXXXXX XXXXXXX XXXXX X X XXXXXXX XXXXXX XXXXXXX XXXXX X X XXXXXXX XX XXXXXXXX
           gettext(u'Top gamers') 
        XXXXX
        BB BBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXX
            BBB BBBBBB BB BBBBBBBBBBBB
              XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBB
                XXXX XXXXXX XXXXXX
                     XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                BBBB
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                BBBBB
                XXXX XXXXXXXXXXXXX XXXXXXXXX
                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX
                     XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX
                    FFFFFFFFFFFFFFFF
                  XXXX
                  XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'tables') XXXX
                XXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                  XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                  XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXX
              XXXXXX
            BBBBBB
          XXXXXX
        BBBB
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'No players registered for this location') XXXX
        BBBBB
      XXXXXXXXXX

      
      BB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBB
      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXXXX
        XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'You follow this location') XXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'New tables will appear on your homepage.') XXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXX
              XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X X XXXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXX XXXX XXXX XXXX XXXXX XXXXX X XXXXX XXXXX XXX X X X XX XXXXX XXX XXX X X X XXXXXX XXXXXXX X XXXXX XXXXX XXXXX XXXX X XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXX X X XXXXXXX XXXX XXXXXX XXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXX XXXXXXXXXXXXXX XX
            XXXXXX
            
          XXXXXXX
          XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXX X XXXXXX XXXX X XX X XXXXXXXXX XXXXXX XX
              XXXXXX
               gettext(u'Unfollow') 
            XXXXXXXXX
          XXXXXXX
        XXXXXX
      XXXXXX
      BBBBB

    XXXXXX

    
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX

        XXXX XXXXXXXXXX XXXXXXXXXXX

        
        BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBB
          XX XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBX
             XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXX
             gettext(u'Create table here') 
          XXXX
        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
          XX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
             gettext(u'Only members can create tables here.') 
          XXXX
        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB
          XX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
             gettext(u'Only owners and managers can create tables here.') 
          XXXX
        BBBBB

        
        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXX
          BB BBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX
               XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXX X X X XXX X X X X X X X XXX XXXXXXXX
               gettext(u'Manage location') 
            XXXX
          BBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBBB
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX
                 XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXX XX XX XXXXXXX XXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXXX XXXXX XXXXX XXXXX X X XXXXXXX XXXXXXXXXXX XXXXX X X X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXXXXXX XXXXX X X X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXX XXXXX XXXXX X X X XXXXXXXXXXXXXXXXX XXXXX X X X XX XXXXXXX X XXXXXXX XXXXX XXXXXXXXXXX XXXXX X X X XXXXX XXXXX XXXXX XXXXX X X X XXXXX XXXXXXXXXXX XXXXX X X X XX XXXX XXXXXXXX
                 gettext(u'My membership') 
              XXXX
            BBBB BBBBBBBBBBBBBBBBBBBBBB
              XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXX X X X XXXX X X X X X X XX XXX XXXXXXXX
                 gettext(u'Membership pending') 
              XXXXXXX
            BBBB
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX
                 XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                 gettext(u'Request membership') 
              XXXX
            BBBBB
          BBBBB

        XXXXXX

        XXX XXXXXXXXXXXXXXXXXXXXXXXXX

        
        BB BBBBBBBBBBBBBBBBBBBBBB
          XXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXX X X X XXXX X X X X X X XX XXX XXXXXXXX
               gettext(u'Opening hours') 
            XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
            XXXXXXXX
            XXXXXXXXX XX X
              XXXXX XXXX X X
                X gettext(u'Monday') XX
                X gettext(u'Tuesday') XX
                X gettext(u'Wednesday') XX
                X gettext(u'Thursday') XX
                X gettext(u'Friday') XX
                X gettext(u'Saturday') XX
                X gettext(u'Sunday') XX
              XX
              XXXXX XXXXXX X X gettext(u'Closed') XX
              XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXX X X XX X X XX XXXX X
                XXXXX X X XXXXXXX XX XXXXXXXXXXXXXXXX
                XXXXX XXXXXX X X XX XXXXXXXXX XXX XXXXXX
                XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXX
                XX XX X XX XXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXX XXXXXXXXX
                XXX XXXXXXXXX X XXX
                XX XXXXXXXXX X
                  XXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X XXXX X
                  XXXXX XXXXX X XX XX XXXXXXXX XX XXX
                  XXXXXXXXX X XXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                X
                XXXXXXXXXXXXX X X
                  XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXXXXXX
                  XXXXXXX
                  XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
              X
            XXXXX
            XXXXXXXXX
          XXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB

        
        BB BBBBBBBBBBBBBBBB
          XXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X X X XXX X X X X X X X XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXX XXXXXXXX XXX X X X XX XXX XXXXXXXX
               gettext(u'How to get there') 
            XXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFX
               XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
               XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              
            XXXX
            BB BBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXX
                XXXXX XXXXXXXX XXXXXXXXX X
                  XXXXX XXXXX X XXXXXXXXXXXX
                  XXXXX XXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXX XXXXX X XXXX XX
                    XXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXX
                  XXX
                  XXXXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXX XX
                  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                X
              XXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXX
            BBBB
              XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX X X XXXXXXX XXXXXXX XXXXXXXXXX XXXX X XXXX X XXXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXX XXXXXXXX
                 gettext(u'Map not available') 
              XXXXXX
            BBBBB
          XXXXXX
        BBBBB

        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX

  
  XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXX
    BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBB
      XX XXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBX
         XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXX
         gettext(u'Create table here') 
      XXXX
    BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
      XX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Only members can create tables here.') XXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXX X X X XXXX X X X X X X XX XXX XXXXXXXX
             gettext(u'Membership pending') 
          XXXXXXX
        BBBB
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX
             XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
             gettext(u'Request membership') 
          XXXX
        BBBBB
      BBBBB
    BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB
      XX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Only owners and managers can create tables here.') XXXX
    BBBBB
  XXXXXX

BBBBBBBB BBBBBBB


BBBBB BBBBBBBBBBB
  XXXXXXXX
    XXXXXXXX XXXXXXXXXXXX X
      XXXXX XXXXXXXXXX X XXX XXX XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XX X XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    X XXXXXXXXXX X XXXXXX X XXX
      XXXXX XXXXXX   X XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXX XXXXXXXX X XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXX X XXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     X XXXXXXXXXX X XXXXXXXX X XXXXXXX
    X
  XXXXXXXXX
BBBBBBBB

BBBBB BBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFXXXXXXXXX
BBBBBBBB
