BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Manage') XXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Permissions') XXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Control who can create and join tables at this location.') XXXX
  XXXXXX

  BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX
      XXXXXX
      XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Membership not enabled') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
           gettext(u'Members only options are disabled because membership management is not active for this location.') 
          XX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Contact us.') XXXX
        XXXX
      XXXXXX
    XXXXXX
  BBBBB

  XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB

    
    XXXX XXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Who can create tables?') XXXX
      BBB BBBBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
                     XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX
          BBBB
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXBBBBXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXBBBBBXX
              XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                     BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXBBBBB
                     XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX
          BBBBB
        BBBBBBB
      BBBBBB
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXX
      BBBBB
    XXXXXX

    
    XXXX XXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Who can join tables?') XXXX
      BBB BBBBBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
                     XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX
          BBBB
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXBBBBXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXBBBBBXX
              XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                     BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXBBBBB
                     XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX
          BBBBB
        BBBBBBB
      BBBBBB
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXX
      BBBBB
    XXXXXX

    XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
       gettext(u'Save permissions') 
    XXXXXXXXX
  XXXXXXX

BBBBBBBB BBBBBBB
