BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Account') XXXX X
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Locations') XXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBB gettext(u'Edit location') BBBB gettext(u'New location') BBBBB
    XXXXX
  XXXXXX

  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    
    
    
    

    
    XXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
      
      BB BBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
    XXXXXX

    
    XXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
      
      BB BBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
    XXXXXX

    
    XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Cover image')  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBB
        XXXX XXXXXX XXXXXX
             XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXX
      BBBBB
      XXXXXX XXXXXX
             XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXX X X X XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX X X X XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXX X X X XXXXXXXXXXXXX XXX X X XXXXXXXXXXXXXXXXXX XXX X X X XXXX XXXXXXXX XXX X X X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X X XXXXX X XXXXXXXX X X X XXX XXX XXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXX gettext(u'Choose an image…') XXXXXXX
        
      XXXXXXXX
      BB BBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
    XXXXXX

    
    XXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
      
      XX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u"We'll use this to show the location on the map.") XXXX
      BB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
    XXXXXX

    
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

    
    XXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
         XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXX
      XXXXXXXX
      
      BB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
    XXXXXX

    
    XXXXXX XXXXXX
           XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Public location') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'Public locations (bar, café, game shop…) can be used by other gamers to organize tables.') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX
               XXXXX
               XXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXX XXXXX
               BB BBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
        XXXX XXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXXXX

    
    XXXX XXXXXXXXXXX XXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX
         XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX X XXXX X XXXXXXXXX XXXXXX XXXXXXXX
         gettext(u'Cancel') 
      XXXX
      XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX X X XXXXXXX XXXXXXXX
        BB BBBBBBBBBBBBBBBB gettext(u'Save changes') BBBB gettext(u'Create location') BBBBB
      XXXXXXXXX
    XXXXXX

  XXXXXXX

BBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBB
  
  XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
      XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXX XX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
          XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX X X gettext(u'Choose an image…') XX
        XXX
      X
    XXX
  XXXXXXXXX
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB
