BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBBBBXXXX XXXXBBBBBBBB

BBBBB BBBBBBB

  
  XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXX
    XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
      XXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Calendar') XXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
      
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
                     XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXX XX
        XXXXXX
      XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
                     XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XX
        XXXXXX
      XXXXXXXXX
      
      BB BBBBBBBBBB
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
           gettext(u'Normal') 
        XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Reservations') 
        XXXXXXXXX
      XXXXXX
      BBBBB
    XXXXXX
  XXXXXX

  
  BB BBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
       gettext(u'Select a group then click cells to reserve them. Click again to remove.') 
    XXXX
    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
      
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
               XXXXXXX gettext(u'Group color') X
               XXXXXXXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'New group...') X
               XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXX XXXXX
               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXX gettext(u'Add group') XX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XX
          XXXXXX
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  BBBBB

  
  XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX

      XXXXXXX
        XXXX
          XXX XXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
                     XXX XXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
               gettext(u'Table') 
            XXXXXXX
          XXXXX
          BBB BB BB BBBBBBBBBBBB
          XXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXX
                     XXXXXXXXXXXXX XXXXXXXXX
                     BB BBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBXXXXXXXXXX XXXXXXXXXXXXXXXXXXBBBBB
                     BB BBBBBBBBBBBBBXXXXXXXXXXXXBBBBXXXXXXXXXXXBBBBBXX
            BB BBBBBBBBBBBBBBBB
              XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXFFFFFFFFXXXXXXX
            BBBB
              XXXXX XXXXXXXXXXXX XXX XXXXXXXXXXXXXXX
            BBBBB
            XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXFFFFFFFFXXXXXXX
            BB BBBBBBBBBBB
              XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFFFXXXXXXX
            BBBB
              XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXBBBBBXXFFFFFFFFXXXXXXX
            BBBBB
            XXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
              BB BBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXFFFFFFXXXXXXX
              BBBBB
            XXXXXX
          XXXXX
          BBBBBB
        XXXXX
      XXXXXXXX

      XXXXXXX
        BBB BBB BB BBBB
        XXXX
          XXX XXXXXXXXXXXXX XXXXXX XXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
                     XXX XXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            XXXXXX
          XXXXX

          BBB BBBB BB BBBBBBBBB
          XXX XXXXXXXXXXX
              XXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXX XXXXXXXX
                     BB BBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBXXXXXXXX XXXXXXXXXXXXXXXXXXBBBBB
                     BB BBBBBBBBBBBBBBBXXXXXXXXXXXBBBBBXX

            XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBB
                XXXX XXXXXXXXXXX XXXXXXXX XXXXXX XXXXXX XXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXX
                  BBB BBBBBBB BB BBBBBBBBBBBBB
                  XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBX
                     XXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXX XXXXXXX
                            XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                    XXXXXXX
                    XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
                  XXXX
                  BBBBBB
                XXXXXX
              BBBBB
              XXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXXFFFFFFFFFFFFX
                   XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXX XXXXXXX
                          XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                   XXXXXXX gettext(u'Add session') XX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XX
                  XXXXXX
                XXXX
              XXXXXX
            XXXXXX

          XXXXX
          BBBBBB
        XXXXX
        BBBBBB
      XXXXXXXX

    XXXXXXXX
  XXXXXX

BBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBB
XXXXXXXX
XXXXXXXXX XX X
  XXXXX XXXXXXXX       X XFFFFFFFFXX
  XXXXX XXXXXXX        X XXXXXXXXXX    X XXXXXXXXX
  XXXXX XXXXXXXXXX     X XXXXXXXXXXXXX X XXXXXXXXX

  XXXXX XXXXXXXXXXXX X X
    XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
  XX

  XXXXX XXXXXXXXXXXXXX X X
    X XXX XX XXXXX XXXXXXXXXX XXXXXX XXXXXXXXX XX
    X XXX XX XXXXX XXXXXX     XXXXXX XXXXXXXXX XX
    X XXX XX XXXXX XXXXXX     XXXXXX XXXXXXXXX XX
    X XXX XX XXXXX XXXXXX     XXXXXX XXXXXXXXX XX
    X XXX XX XXXXX XXXXXX     XXXXXX XXXXXXXXX XX
  XX

  XX XX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXX         X XXXXXX
  XXX XXXXXXXXXXXXXXX X XXXXX
  XXX XXXXXX          X XXXXXXXXXXXXX
  XXX XXXXXXXXXXXX    X XXXXXXXXXXXXXXXXXXX XX X XXXXXXXXXX XXXXXXXXX XXXXX XXXXXX X

  XX XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX XXXXXXXXXXXX X
    XXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX X
    XXXXX X XXXXXX XXXXXXXXXXXXXXX X
  X
  XXXXXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X

  XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX X
    XXXXX X XXXXXX XXX X
  X
  XXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X

  XX XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXX XXXXXX X
    XXXXX X X XXXXXXXXXXXXXXXXXXXXX XXX XXXX
    XXXXX X X XXXXXXXXXXXXXXXXXXXXX XXX XXXX
    XXXXX X X XXXXXXXXXXXXXXXXXXXXX XXX XXXX
    XXXXXX XXXXXXX X X X XXX X X X XXX X X X XXX X XXXXX X XXXX
  X

  XX XX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXX   X XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
  XXXXX XXXXXXXX X XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX

  XXXXXXXXXXXXXXXX X XXXXXXXX XXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXX X XXXX XXXXXXXXX XXXXXXXX XXX
  XX

  XX XX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXX X XXXXXXXX XXXX X
    XXXXXXX X XXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX    X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX X XXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   X XX X XXXXXX   X XXXXXXXXX

    XX XXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    X XXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX X XXXXX
    X
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX
  XX

  XX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXX X XXX
    XXXXXXXXXXXXXXXXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXX X
    XXXXX X X XXXXXXXXXXXXXXXXXXXX XXX X XXXXXX XXXX XXX XXX XXX
    XX XXXX XXXXXXX
    XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX X XXXXXX XXXXXXXXX XXX XXX XXX
    XXXXX XXX X XXXXXXXXXXXXXXX
      X XXXXXXXXXX XX XXXXXX XX X XXXXXX X XXX XXXXXXXX XXXXXXX XXXXX XXXXX XX XXX XXXXXXXXXXXXXX
      X XXXXXXXXXX XX XXXXXX XX X XXXXXX X XXXXX
    XX XXXXXXXXXXXXXXX XXXXXXX
    XXXXXX X XXXXXXXXXXXXXXXXXXXXXX XXX X XXXXXX XXXX XXX XXX XXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X
      XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXX XXXXXXXXXXXXXXXXXX
    XXX
    XXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXXXXXXXXXXX X XXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX X XXX
    XXXXXXXXXXXXXXXXXXXXXXX XXX X
      XXXXX XXXXXXXXXX X XXXXXXX XX XXXX XXX XXXXXXXXXXXXXXXX

      XX XXXXXXX XXXX
      XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX X X XXXXXXX X XXX X
        XXXXXXXXXXXXX X XXXXXXXXXXX X XXXXXXX X XXXXXXXX X XXX X
        XXXXXXXX X XXXXXXXXXXX X XXXXXXX X XXXXXXXX X XXX X
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

      XX XXXXXX XXXXXX XXXX X XXXXX
      XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX X XXXXXXXXX
      XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X XXXX
      XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXX X XXXXXXXX XX X XXXXXXXXXXXXXXXXXX XX

      XX XXXXXX XXXXXX XXX
      XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX X XXXXXXXXX
      XXXXXXXXX X XXXXXXXX XXXXXXXX
      XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX X XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX X XXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX X XXXX
      XXXXXXXXXXX X XXXXXXXX XXX X XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX

      XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
  X

  XXXXXXXXXXXXXXX X XXXXXXXX XX X
    XXXXX XXXXX       X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX  X XXXXXXXXXXXXXXXXXXX
    XX XXXXXXX X XXXXXXXXXXXXXX XXXXXXX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXX
    XXXXX XX    X XXXXXXXXXXX
    XXXXXXXXXXXXX XXX XXXXX XXXXX XXX
    XXXXXXXXXXXXX
    XXXXXXXXXXX X XXX
    XX XXXXXXX XXXXXX XX XXXX XXXXXXX XXXXX XXX XXXXXXXXXXX
    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
  XX

  XX XX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX X XXXXXXXX XXX XXXX XXXX X
    XX XXXXXXXXXX XXXXXXX
    XX XXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX

    XXXXX XXX   X XXX X XXX X XXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXX XXX X XXXXXX XXXX XXX XXXXXXXXXXXXXXXX XXX
    XX XXXXXXXX XXXXXXX

    XX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX X
      XXXXXX XXXXXXXXXXXXXXXXXX
    X XXXX X
      XXXXXXXXXXXXXXXXX X X XXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXX XX
    X
    XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX
  XX

  XX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX XXXXXXXXXXXX XXXX X
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXX X XXX X XXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
    XX XXXXX XXXXXXXX XXXXXXXXXXX XXXXXX XXX XXXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X
      XXXXX XXX   X XXXXXXXXXXXXXXXXXX
      XXXXX XXXXX X XXXXXXXXXXXXXXX
      XXXXX XXX   X XXXXXXXXXXXXXXXXXXX
      XXXXX XXX   X XXXXXXXXXXXXXXXXXXX
      XXXXX XXXX  X XXXXXXXXXXXX XXXXX
      XX XXXXXXX XXXXXXX

      XX XXXXXX XXXXXXXXXX XXXXXXXXX XX XXXXXXXXXXX XXXX XX XXXXXXXXXXXX XX XXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX XXXXXXX X XXXX X XXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XX XXXXX XXXXX XX XXX XX XXXX
      XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX X XXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX X XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXX X XXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX
    XXX
  X

  XX XX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX
  XXX

XXXXX
XXXXXXXXX

XXXXXXX
  XX XXXXXXXXXXX XXXXX XXXX XXXXXXXX XXX XXX XXXXXXX XXXX XXXXXX XX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
    XXXXXXX XXXXX
  X
  XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXX XXXXXXXX
  X

  XX XXXX XXXXXXX XXXXXXX XXXXX XXX XXXXXXXXXXX XXXXX XX
  XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
    XXXXXXXXXXXX XXXXX
  X
XXXXXXXX
BBBBBBBB BBBBBBBBBBB
