BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXX

  
  XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Request Membership') XXXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Request Membership') XXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
       gettext(u'Request a membership for %(name)s. A manager will review your request.') SSSSSSS S SSSSSSSSSS SSS SSSSSSSSS S SSSSSSS SSSS SSSSSS SSSS SSSSSSSS
    XXXX
  XXXXXX

  XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX
    BBBBBBBBBB

    XXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
      XXXXXXXXX XXXXX
                XXXXXXXXXXXX
                XXXXXXXX
                XXXXXXXXXXXXXFFFFFFFFFFX
                XXXXXXXXXXXXX XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXBBBBB XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXFFFFFFFFFFXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
    XXXXXX

    XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XXXXX XXXXXXXXXXXX XXXXXX X X X XXXXXX XX XXXXXX XXXXXX X X X XXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX
       gettext(u'Send Request') 
    XXXXXXXXX
  XXXXXXX

  XX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Back to location') XXXX
  XXXX

XXXXXX
BBBBBBBB BBBBBBB
