BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Manage location') XXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Widget') XXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Embed the upcoming tables of your location on any website.') XXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX

    
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Basic snippet') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u"Copy and paste this code into your website's HTML.") XXXX

      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXX
XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBBBXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
           gettext(u'Copy') 
        XXXXXXXXX
      XXXXXX
    XXXXXX

    
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'English version') XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Add data-lang to display the widget in English.') XXXX

      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXX
XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBBBXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
           gettext(u'Copy') 
        XXXXXXXXX
      XXXXXX
    XXXXXX

    
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Notes') XXXX
      XXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX
        XXXX gettext(u'The widget automatically shows upcoming open tables for your location.') XXXXX
        XXXX gettext(u'Your location slug is <strong>%(slug)s</strong> — do not change it.') SSSS SSSSSSSS SSSS SS SSSSSSSSSSSSSSSSSSSSSSSSS S SS SSS SSSSSS SSSXXXXX
        XXXX gettext(u'Supported attributes: data-location, data-lang (default: it).') XXXXX
        XXXX gettext(u'You can place the snippet anywhere inside the body of your page.') XXXXX
      XXXXX
    XXXXXX

  XXXXXX

  XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXX XXXX X
      XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX X X gettext(u'Copied!') XX
        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX X XXXXXXXXX XX XXXXXX
      XXX
    X
  XXXXXXXXX

BBBBBBBB BBBBBBB
