BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Manage location') XXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Table statistics') XXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Generate a message to share table status on WhatsApp or other chats.') XXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX

    
    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'From') XXXXXXXX
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'To') XXXXXXXX
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Generate') 
          XXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXX XXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBBXXXXXXXBBBBB
                 XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Show full tables') 
        XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBXXXXXXXBBBBB
                 XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Show closed tables') 
        XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBXXXXXXXBBBBB
                 XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Show player names') 
        XXXXXXXX
      XXXXXX
    XXXXXXX

    
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Message') XXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
           gettext(u'Copy') 
        XXXXXXXXX
      XXXXXX
      XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
                XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

  XXXXXX

  XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXX X
      XXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX X X gettext(u'Copied!') XX
        XXXXXXXXXXXXXXXXXXX XX X XXXXXXXXXXXXXXX X XXXXXXXXX XX XXXXXX
      XXX
    X
  XXXXXXXXX

BBBBBBBB BBBBBBB
