BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Manage') XXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Location info') XXXXX
  XXXXXX

  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    
    
    
    

    
    XXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
      
      BB BBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
    XXXXXX

    
    XXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
      
      BB BBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
    XXXXXX

    
    XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Cover image')  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBB
        XXXX XXXXXX XXXXXX
             XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXX
      BBBBB
      XXXXXX XXXXXX
             XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXX X X X XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX X X X XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXX X X X XXXXXXXXXXXXX XXX X X XXXXXXXXXXXXXXXXXX XXX X X X XXXX XXXXXXXX XXX X X X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X X XXXXX X XXXXXXXX X X X XXX XXX XXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXX gettext(u'Choose an image…') XXXXXXX
        
      XXXXXXXX
      BB BBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
    XXXXXX

    
    XXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
      
      XX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u"We'll use this to show the location on the map.") XXXX
      BB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
    XXXXXX

    
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

    
    XXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
         XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXX
      XXXXXXXX
      
      BB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
    XXXXXX

    
    
    XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Opening hours')  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    
    XXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
      
      XX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Used as the default start time when creating a new table here. You can still pick a different time for each table.') XXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
    XXXXXX

    
    XXXXXX XXXXXX
           XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Public location') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'Public locations (bar, café, game shop…) can be used by other gamers to organize tables.') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX
               XXXXX
               XXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXX XXXXX
               BB BBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
        XXXX XXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXXXX

    
    XXXXXX XXXXXX
           XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Show tables in homepage') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'When enabled, upcoming tables from this location appear in the homepage feed.') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX
               XXXXX
               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXX XXXXX
               BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
        XXXX XXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXXXX

    
    XXXX XXXXXXXXXXX XXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX
         XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX X XXXX X XXXXXXXXX XXXXXX XXXXXXXX
         gettext(u'Cancel') 
      XXXX
      XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX X X XXXXXXX XXXXXXXX
         gettext(u'Save changes') 
      XXXXXXXXX
    XXXXXX

  XXXXXXX

BBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBB
  XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
      XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXX XX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
          XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX X X gettext(u'Choose an image…') XX
        XXX
      X
    XXX
  XXXXXXXXX
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  XXXXXXXX
  XXXXXXXXX XX X
    XXXXX XXXX X X
      X gettext(u'Monday') XX
      X gettext(u'Tuesday') XX
      X gettext(u'Wednesday') XX
      X gettext(u'Thursday') XX
      X gettext(u'Friday') XX
      X gettext(u'Saturday') XX
      X gettext(u'Sunday') XX
    XX
    XXXXX XXXXXXXXXXXX X X gettext(u'Closed') XX
    XXXXX XXXXXXXXXXXXXX X X gettext(u'+ Add time slot') XX

    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXXX X
      XXX X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXX XX XXX X XXXXX XXX X XXXXXX XXX X
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX X
      XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXX X XXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXXXXX
      XXXXXXXXXXXXX X X
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Remove') XX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX XXX XXXX XXX XXXXXXXX
        XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXXXXXXXXXX
      XXX
      XXXXXX XXXX
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X
      XXXXX XXXXXX X XXXXXXXXXXXXXXX XXX XXXXXX
      XXXXX XXXXX  X XXXXXXXXXXXXX XX XXX

      XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
      XXXXXXXXXXXXXXXX X XXXXXXXXX

      XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX X X
        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXX X XX X XXXXXXXXXXX
            XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX

      XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXX X XX X X XXXXXXXXX

      XX XXXXXXXXXXXXX XXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
      X XXXX X
        XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX XXX XXXXXXX XX XXXXXX
      X

      XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXX X XXXXXXXXX
      XXXXXXXXXXXXXXXX X XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXX
      XXX
      XXXXXXXXXXXXXXXXXXXXXXXXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXX

      XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXX
    X

    XXXXXXXX XXXXXXXXXXXXXXXX X
      XXXXX XXXX X XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX X       X XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXX   X XXX
        XX XXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXX
              XXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
          XXX
        X
        XXXXXXX X X XXXXXXXX XXXXXXXX XXXXXX XXXXX XX
      XXX
      XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
    X

    XX XXXXX XX
    XXXXX XXXXXXXX X XXXXXXXXXXX
    XXX XXXX X X XX X X XX XXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX X XXXXXXXX XXXXX XXXXXX XX XXXX
    X

    XX XXXXXXXXX XXXXXX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXXX
  XXXXXXXXX
BBBBBBBB
