BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB
  
  XXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXXXXXXX XXXX XXXXXXXXXXX
      XXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXX XXXXXXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXX XXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXXX X XXX XXX XXXX XXXXX X X X XXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    X
  XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Manage') XXXX X
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Members') XXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      BB BBBBBB gettext(u'Add member') BBBBBBBBB
    XXXXX
  XXXXXX

  XXXXX XXXXXXXXXXXXX
        XXXXXXXXBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBX
        XXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB

    BBB BBBBB BB BBBB
      BB BBB BBBBBBBBBBBBBBB
        XXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
            
            BB BBB BBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXXBBBBB
          XXXXXXXX
          
          BB BBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
        XXXXXX
      BBBBB
    BBBBBB

    XXXX XXXXXXXXXXX XXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX
         XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX X XXXX X XXXXXXXXX XXXXXX XXXXXXXX
         gettext(u'Cancel') 
      XXXX
      XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX X X XXXXXXX XXXXXXXX
        BB BBBBBB gettext(u'Add member') BBBB gettext(u'Save changes') BBBBB
      XXXXXXXXX
    XXXXXX

  XXXXXXX

  BB BBB BBBBBB BBB BBBBBB
    XXXX XXXXXXXXXXXXXXX XXXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Membership history') XXXXX

      BB BBB BBBBBBBBBBB
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'No memberships yet.') XXXX
      BBBB
        XXXX XXXXXXXXXXXXXXXXXX
          BBB BB BB BBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
              XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXX
                  
                  BB BBBBBBBBB BB BBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Active') XXXXXXX
                  BBBB BBBBBBBBB BB BBBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Pending') XXXXXXX
                  BBBB BBBBBBBBB BB BBBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Expired') XXXXXXX
                  BBBB BBBBBBBBB BB BBBBBBBBBB
                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXX gettext(u'Rejected') XXXXXXX
                  BBBBB

                  
                  XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBXBBBBB
                     gettext(u'to') 
                    BB BBBBBBBBBBBBBBBXBBBBB
                  XXXX

                  BB BBBBBBBB
                    XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                  BBBBB
                  BB BBBBBBBBBBBBBB
                    XX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Approved by') X XXXX
                  BBBBB
                XXXXXX

                
                XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                          XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                     gettext(u'Edit') 
                  XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBX
                          XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBXFFFFFFFFFFFFBB BBBBBBBBBBB X FFFFFFFFFFFFBBBBBXBBBBBXX
                     gettext(u'Delete') 
                  XXXXXXXXX
                XXXXXX
              XXXXXX

              
              XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXXX
                  BBBBBBBBBB

                  
                  XXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Status') XXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBBXXXXXXXXBBBBBX gettext(u'Pending') XXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBX gettext(u'Active') XXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBBXXXXXXXXBBBBBX gettext(u'Expired') XXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBX gettext(u'Rejected') XXXXXXXXX
                    XXXXXXXXX
                  XXXXXX

                  
                  XXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Start Date')  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                           XXXXXXXFFFFFFFFFFFFFFFFFFFFFFX
                           XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX

                  
                  XXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'End Date')  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                           XXXXXXXFFFFFFFFFFFFFFFFFFFFFFX
                           XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX

                  
                  XXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Notes')  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXXXXXXXXXX
                    XXXXXXXXX XXXXXXXXXXXX XXXXXXXX
                              XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX

                  XXXX XXXXXXXXXXX XXXXX XXXXXX
                    XXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                       gettext(u'Cancel') 
                    XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                       gettext(u'Save') 
                    XXXXXXXXX
                  XXXXXX
                XXXXXXX
              XXXXXX
            XXXXXX
          BBBBBB
        XXXXXX
      BBBBB

      XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
           gettext(u'New membership') 
        XXXXXXXXX
      XXXXXXX
    XXXXXX
  BBBBB

  
  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXX XXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Delete membership') XXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Cancel') 
          XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Delete') 
          XXXXXXXXX
        XXXXXX
      XXXXXXX
    XXXXXX
  XXXXXX

BBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
  XXXXXXXX
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
    XXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB
