BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB
  
  XXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXXXXXXX XXXX XXXXXXXXXXX
      XXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXX XXXXXXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXX XXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXXX X XXX XXX XXXX XXXXX X X X XXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    X
  XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
      XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Manage') XXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Managers') XXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX

    
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Team') XXXX
      XXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

        
        XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXX
          XXXX XXXXXX XXXXXX
               XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
              XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX
            XXXXXX
             gettext(u'Creator') 
          XXXXXXX
        XXXXX

        
        BBB BBBBBBB BB BBBBBBBB
          XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXX
            XXXX XXXXXX XXXXXX
                 XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX XXX XXXX XXX XX
              XXXXXX
            XXXXXXXXX
          XXXXX
        BBBBB
          XXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'No managers assigned yet.') XXXXX
        BBBBBB

      XXXXX
    XXXXXX

    
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Add manager') XXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXX
        BBBBBBBBBB
        XXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XX
          XXXXXX
           gettext(u'Add') 
        XXXXXXXXX
      XXXXXXX
    XXXXXX

  XXXXXX

  
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXX XXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Remove manager?') XXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Are you sure you want to remove')  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
           gettext(u'Cancel') 
        XXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Remove') 
          XXXXXXXXX
        XXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

BBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
  XXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
    XXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX
BBBBBBBB
