BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
      XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Manage') XXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Participants') XXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
       ngettext(u'%(n)s person registered', u'%(n)s people registered', count) SSSSS SSSSSS SSSSSSSSSSPPPPP PPPPPP PPPPPPPPPP
    XXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BBB B BB BBBBBBBBBBBB
          XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXX
            XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
              BBBB
                XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
              BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                
                BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  BB BBBBXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXBBBBB
                BBBBBBB
              XXXX
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXBBBBB
              XXXX
            XXXXXX
            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXFFFFFFF FFXXXXXXX
          XXXXX
        BBBBB
          XXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'No participants yet.') XXXXX
        BBBBBB
      XXXXX
    XXXXXX
  XXXXXX

BBBBBBBB BBBBBBB
