BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBB

  
  BB BBBBBBBBBBBB BB BBBBBBBBB
    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXX XXX X X X XXXX X X X X X X XX XXX XX
      XXXXXX
      XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Pending approval') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'This event is awaiting admin approval and is not yet visible to the public.') XXXX
      XXXXXX
    XXXXXX
  BBBBB

  
  XXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXX XXXXXXXX XXXX XXXXXXXX
         XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXXXX

      BB BBBBBBBBBB
        XX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X X X XXX X X X X X X X XXX XX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXX XXXXXXXX XXX X X X XX XXX XX
          XXXXXX
          
        XXXX
      BBBBB

      XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX

      BB BBBBBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X X XX XXXXXX XX
          XXXXXX
          BBB BBBBBBBBBB BB BBBBBBBBBBB
            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
              FFFFFFF F FF
            XXXXXXX
          BBBBBB
        XXXXXX
      BBBBB

      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX

        
        BB BBBBBBBBBBBB BB BBBBBBBBBB
          BB BBBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBB
              XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX X X XXXXXXX XX
                XXXXXX
                 gettext(u"You're attending") 
              XXXXXXX
            BBBB
              XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBB BBBBBBBBBBXX
                BBBBBBBBBB
                XXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX
                  XXXXXX
                   gettext(u'Attend this event') 
                XXXXXXXXX
              XXXXXXX
            BBBBB
          BBBB
            XX XXXXXXBBB BBBBBBBXXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX
               XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX
              XXXXXX
               gettext(u'Log in to attend') 
            XXXX
          BBBBB
        BBBBB

        
        XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBX
           XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
           gettext(u'See the program')  X
        XXXX

      XXXXXX
    XXXXXX
  XXXXXXXXXX

  
  XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX

    
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

      
      BB BBBBBBBBBBBBBBBBB
        XXXXXXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'About') XXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBB B BBB
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                      XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                      XXXXXXXXXXXXXXX X XXXXXXXX X X gettext(u'Read more') X X X gettext(u'Show less') XX
                    X
                    XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
               gettext(u'Read more') 
            XXXXXXXXX
          BBBB
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
          BBBBB
        XXXXXXXXXX
      BBBBB

      
      BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBB
          XXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Sponsored by') XXXXX
            XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
              BBB BBB BB BBBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBX
                   XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  BB BBBBBBBBB
                    XXXX XXXXXX XXXXXX
                         XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                  BBBB
                    XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X X X XXX X X X X X X X XXX XX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXX XXXXXXXX XXX X X X XX XXX XX
                      XXXXXX
                    XXXXXX
                  BBBBB
                  XXXXX
                    XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBB
                  XXXXXX
                XXXX
              BBBBBB
            XXXXXX
          XXXXXXXXXX
        BBBBB
      BBBBBBB

      
      XXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBX
           XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X X XX XXXXXXXXXX XX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXX XXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'See the program') XXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
              BB BBBBBBBBBBB
                 ngettext(u'%(n)s table scheduled', u'%(n)s tables scheduled', count) SSSSS SSSSS SSSSSSSSSPPPPP PPPPPP PPPPPPPPP
              BBBB
                 gettext(u'Browse the schedule by time, area and game') 
              BBBBB
            XXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XX
          XXXXXX
        XXXX
      XXXXXXXXXX

      
      XXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Your tables') XXXXX

        BB BBBBBBBBBBBBBBBBBBBBB
          BB BBBBBBBBBBBBBBBB
            
            BB BBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX
                XXXXXX
                XXXXX
                  XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Overlapping tables') XXXX
                  XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'Two of the tables you joined overlap in time. Check your schedule below.') XXXX
                XXXXXX
              XXXXXX
            BBBBB

            XXXX XXXXXXXXXXXXXXXXXX
              BBB BBB BB BBBBBBBBBBBBBBBB
                XXXXX
                  XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X X XX XXXXXX XX
                    XXXXXX
                    FFFFFFFF F F FF
                  XXXXX
                  XXXX XXXXXXXXXXXXXXXXXX
                    BBB BBBB BB BBBBBBBBB
                      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXX
                          XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXX X X X XXXX X X X X X X XX XXX XX
                            XXXXXX
                            FFFFFFFFFF
                          XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
                          BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBB
                        XXXXXX
                      XXXXXX
                    BBBBBB
                  XXXXXX
                XXXXXX
              BBBBBB
            XXXXXX
          BBBB
            
            XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX X X X XXXXXXX XXXX XXXX X X XXXXXXXXXXXXXX XXXXXXX XXXXX X X X XXXX XXXXXXXXXXXXX X XXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX
              XXXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u"You haven't joined any table yet!") XXXX
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Browse the program and grab a seat at a table.') XXXX
              XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBX
                 XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'See the program')  X
              XXXX
            XXXXXX
          BBBBB
        BBBB
          
          XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX X X X X X XXX XXX X X X XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X X X X XXXXX XXXXXX XX
            XXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Log in to see your tables') XXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Sign in to keep track of the tables you join at this event.') XXXX
            XX XXXXXXBBB BBBBBBBXXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX
               XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Log in')  X
            XXXX
          XXXXXX
        BBBBB
      XXXXXXXXXX

      
      BB BBBBBBBBBBB
        XXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXX XXXXXX XXXXX XXXXX XX XX XXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXX XX
              XXXXXX
              XXXX XXXXXXXXXXXXX XXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Add your phone number') XXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
                   gettext(u'Leave a phone number so the organizers can reach you for last-minute changes.') 
                XXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBX
                      XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX
                  BBBBBBBBBB
                  XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                           XXXXXXXXXXXX gettext(u'Phone number') X
                           XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXXXXX XXXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                     gettext(u'Save number') 
                  XXXXXXXXX
                XXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXXXXXX
      BBBBB

    XXXXXX

    
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXX

          
          BB BBBBBBBBBBBB BB BBBBBBBBBB
            XXXXX
              BB BBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                      XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX X X XXXXXXX XX
                    XXXXXX
                     gettext(u"You're attending") 
                  XXXXXX
                BBBB
                  XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBB BBBBBBBBBBXX
                    BBBBBBBBBB
                    XXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX
                      XXXXXX
                       gettext(u'Attend this event') 
                    XXXXXXXXX
                  XXXXXXX
                BBBBB
              BBBB
                XX XXXXXXBBB BBBBBBBXXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX
                   XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX
                  XXXXXX
                   gettext(u'Log in to attend') 
                XXXX
              BBBBB
              BB BBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
                   ngettext(u'%(n)s person attending', u'%(n)s people attending', count) SSSSS SSSSSS SSSSSSSSSPPPPP PPPPPP PPPPPPPPP
                XXXX
              BBBBB
            XXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB

          
          BB BBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX
               XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXX X X X XXX X X X X X X X XXX XX
              XXXXXX
               gettext(u'Manage event') 
            XXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB

          
          BB BBBBBBBBBBB
            XXXXX
              XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X X XX XXXXXX XX
                XXXXXX
                 gettext(u'Dates') 
              XXXXX
              XXXX XXXXXXXXXXXXXXXXXX
                BBB BBBBBBBBBB BB BBBBBBBBBBB
                  XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                                 BB BBBBBBBBBBBBBBB BB BBBBBXXXXXXXXXXXXBBBBXXXXXXXXXXXXBBBBBXXXXXXXXX
                    FFFFFFFF F F FF
                  XXXX
                BBBBBB
              XXXXXX
            XXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB

          
          BB BBBBBBBBBBB BB BBBBBBBBBBB
            XXXXX
              XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXX XX XX XXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXX XX
                XXXXXX
                 gettext(u'Contacts') 
              XXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBB
                  XX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXX XX XX XXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXX XX
                    XXXXXX
                    
                  XXXX
                BBBBB
                BB BBBBBBBBBBB
                  XX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXX XXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXX XXXXXXXXXX XXXX X X XXXXXX XXXXXX XXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXX XX
                    XXXXXX
                    
                  XXXX
                BBBBB
              XXXXXX
            XXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB

          
          BB BBBBBBBBBBBBB
            XXXXX
              XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X X X XXX X X X X X X X XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXX XXXXXXXX XXX X X X XX XXX XXXXXXXX
                 gettext(u'How to get there') 
              XXXXX
              XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFX
                 XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                 XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                
              XXXX
              BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
                  XXXXX XXXXXXXX XXXXXXXXX X
                    XXXXX XXXXX X XXXXXXXXXXXX
                    XXXXX XXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                      XXXXXXX XXXXX X XXXX XX
                      XXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXX
                      XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXX
                    XXX
                    XXXXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXX XX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                  X
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXX
              BBBB
                XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX X X XXXXXXX XXXXXXX XXXXXXXXXX XXXX X XXXX X XXXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXX XXXXXXXX
                   gettext(u'Map not available') 
                XXXXXX
              BBBBB
            XXXXXX
          BBBBB

        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX

BBBBBBBB

BBBBB BBBBBBBBBBB
  BB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFXXXXXXXXX
BBBBBBBB
