BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  
  XXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Events') XXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Conventions, tournaments and game days near you.') XXXX
  XXXXXX

  
  XXXXXXXX XXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Upcoming events') XXXXX

    BB BBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        BBB BBBBB BB BBBBBBBBBBBBBBB
          BBBBBBBBBB BBBBB BBBBB
        BBBBBB
      XXXXXX
    BBBB
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'No upcoming events at the moment. Check back soon!') XXXX
    BBBBB
  XXXXXXXXXX

  
  BB BBBBBBBBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Past events') XXXXX

      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
        BBB BBBBB BB BBBBBBBBBBB
          BBBBBBBBBB BBBBB BBBBB
        BBBBBB
      XXXXXX

      BB BBB BBBBBBBBB
        XXXX XXXXXXXXXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
             gettext(u'See all past events')  X
          XXXX
        XXXXXX
      BBBBB
    XXXXXXXXXX
  BBBBB

BBBBBBBB BBBBBBB
