BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  
  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
    XXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Program') XXXXX
      BB BBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBB
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBXXXXXXFFFFFFFFFFFFBB BBBBBBBBBBBBBXXXXXXBBBBBBBBBBX
             XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XX
            XXXXXX
             gettext(u'Create table') 
          XXXX
        BBBB
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX
             XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XX
            XXXXXX
             gettext(u'Add dates first') 
          XXXX
        BBBBB
      BBBBB
    XXXXXX
  XXXXXX

  
  
  BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBB
    XXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXX
      BBB BBBBBBBBBB BB BBBBBBBBBBBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
           XXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXBBBBXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXBBBBBXX
          FFFFFFF FF
        XXXX
      BBBBBB
      BB BBBBBBBBBBBBBB
        XX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBX
           XXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                  BB BBBBBBBBBXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBBBXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXBBBBBXX
          BB BBBBBBBBB gettext(u'Hide past days') BBBB gettext(u'Show past days') BBBBB
        XXXX
      BBBBB
    XXXXXX
  BBBBB

  
  XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
    BB BBBBBBBBBB
      XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBBX
         XXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                BB BBB BBBBBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXBBBBXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXBBBBBXX
         gettext(u'All areas') 
      XXXX
      BBB BBBB BB BBBBBBBBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBX
           XXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBB BB BBBBBBBXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXBBBBXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXBBBBBXX
          
        XXXX
      BBBBBB
    BBBBB

    BB BBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBB
          XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFFF
            XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBBX
               XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
               XXXXXXX gettext(u'Remove filter') XX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX XXX XXXX XXX XX
              XXXXXX
            XXXX
          XXXXXXX
        BBBB
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXX X X XXX XXX XXXXX XXX X X XXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXX XXX X X XXX XXX XXXXX XXX X X XXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXX X X XXX XXX XXXXX XXX X X XXX XXXXXXX XXXXXXX XX
            XXXXXX
             gettext(u'Filter by game') 
          XXXXXXXXX
        BBBBB
      XXXXXX
    BBBBB
  XXXXXX

  
  BB BBBBBBBBBB
    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
      XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBX
         XXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                BB BBB BBBBBBBBBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXBBBBXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXBBBBBXX
         gettext(u'All categories') 
      XXXX
      BBB BBBBBBBB BB BBBBBBBBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBX
           XXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXBBBBXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXBBBBBXX
          
        XXXX
      BBBBBB
    XXXXXX
  BBBBB

  
  XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
      XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBBX
         XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBB BB BBBBBBXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBBXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XX
        XXXXXX
         gettext(u'Agenda') 
      XXXX
      XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBX
         XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBB BB BBBBBBXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXBBBBBXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX X X X X XXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX X X X X XXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXXXX XXXXXX XXXX X X X XXXXXXXXXXXXXXXXX XXXX X X X XXXXX XXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXX XX
        XXXXXX
         gettext(u'Grid') 
      XXXX
    XXXXXX
  XXXXXX

  
  BB BBBBBBBBBBBBB BBB BBBBBBBBBB
    XXXX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX
      XXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Some tables share a station at overlapping times. Conflicting tables are marked below.') XXXX
    XXXXXX
  BBBBB

  
  BB BBB BBBBBBBBBB
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXX X X X XXXX X X X X X X XX XXX XX
        XXXXXX
      XXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'No tables for the selected filters.') XXXX
    XXXXXX
  BBBB BBBBBBBBB BB BBBBBB
    
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXX
          XXXX
            XXX XXXXXXXXXXXXX XXXXXX XXXX XXXXXXXX XXXXXXXXXXX
            BBB BBB BB BBBBBBBBBBBB
              XXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXX XXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                BB BBBBBBBXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXBBBBB
              XXXXX
            BBBBBB
          XXXXX
        XXXXXXXX
        XXXXXXX
          BBB BBB BB BBBBBBBBB
            XXXX
              XXX XXXXXXXXXXXXX XXXXXX XXXX XXXXXXXX XXXXXXXXXX XXXX XXXXXXXXX XXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
              XXXXX
              BBB BBBB BB BBBBBBBBB
                XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX BB BBBBXXXXXXXXXXXBBBBBXX
                  XXXX XXXXXXXXXXXXXXXX XXXXX
                    BBB BBBBB BB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBB
                  XXXXXX
                XXXXX
              BBBBBB
            XXXXX
          BBBBBB
        XXXXXXXX
      XXXXXXXX
    XXXXXX
  BBBB
    
    XXXX XXXXXXXXXXXXXXXXXX
      BBB BBBB BB BBBBBB
        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXX
          
          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXX X X X XXXX X X X X X X XX XXX XX
              XXXXXX
              FFFFFFFFFF
            XXXXXXX
          XXXXXX
          
          XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBB
          XXXXXX
        XXXXXX
      BBBBBB
    XXXXXX
  BBBBB

  
  XXXX XXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Filter by game') XXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX XXX XXXX XXX XX
          XXXXXX
        XXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBBX
           XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                  BB BBB BBBBBBBBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXBBBBBXX
           gettext(u'All games') 
        XXXX
        BBB BBBB BB BBBBBBBBBBBBBB
          XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBX
             XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBB BB BBBBBBBXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXBBBBBXX
            BB BBBBBBBBBB
              XXXX XXXXXX XXXXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
            BBBB
              XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            BBBBB
            
          XXXX
        BBBBBB
      XXXXXX
    XXXXXX
  XXXXXX

BBBBBBBB
