BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
      XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Manage') XXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Play areas') XXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Drag to reorder. The order will be reflected on the event page.') XXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX

    
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Areas') XXXX
      XXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BBB BBBB BB BBBBB
          XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XX
              XXXXXX
            XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX X X X X XXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX X X X X XXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXXXX XXXXXX XXXX X X X XXXXXXXXXXXXXXXXX XXXX X X X XXXXX XXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXX XX
            XXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBXX
              BBBBBBBBBB
              XXXXXXX XXXXXXXXXXXXX
                      XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Remove this area?') XXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX XXX XXXX XXX XX
                XXXXXX
              XXXXXXXXX
            XXXXXXX
          XXXXX
        BBBBB
          XXX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'No areas added yet.') XXXXX
        BBBBBB
      XXXXX
    XXXXXX

    
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Add area') XXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
          
          BB BBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
        XXXXXX
        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XX
          XXXXXX
           gettext(u'Add area') 
        XXXXXXXXX
      XXXXXXX
    XXXXXX

  XXXXXX

BBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBB
  XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
      XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXX XXXXXXX
      XXX XXXXXXXXXXXXXX X
        XXXXXXXXXX XXXX
        XXXXXXX XXXXXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXX XX X
          XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX X X X
          XXXX
          XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBXX X
            XXXXXXX XXXXXXX
            XXXXXXXX X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX XX
            XXXXX XXXXXXXXXXXXXXXX XXXXX XX
          XXX
        X
      XXX
    XXX
  XXXXXXXXX
BBBBBBBB
