BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBBBB

  
  XXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBB
         gettext(u'Edit table') 
      BBBB
         gettext(u'Create a new table') 
      BBBBB
    XXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX
    XXXX
  XXXXXX

  XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    

    
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      BB BBBBBBBBBBB
        XXXX XXXXXX XXXXXX
             XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
      BBBB
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X X XX XXXXXXXXXX XXXXXXXX
        XXXXXX
      BBBBB
      XXXX XXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Event') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXXX
    XXXXXX

    
    XXXX XXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Details') XXXX
      XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
           XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXX
        XXXXXXXX
        
        BB BBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
      XXXXXX
      XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
           XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXX
        XXXXXXXX
        
        BB BBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
      XXXXXX
    XXXXXX

    
    XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Date and time') XXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
        XXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
          
          BB BBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
        XXXXXX
        XXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
          
          BB BBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
        XXXXXX
        XXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
          
          BB BBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
        XXXXXX
      XXXXXX
    XXXXXX

    
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
           XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXX
        XXXXXXXX
        
        BB BBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
      XXXXXX
    BBBBB

    
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
           XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXX
        XXXXXXXX
        
        BB BBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
      XXXXXX
    BBBBB

    
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
           XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXX
        XXXXXXXX
        
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
      XXXXXX
    BBBBB

    
    XXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
         gettext(u'Game')  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXX
      XXXXXXXX

      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
             XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBXX

      XXXX XXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXBBBBBX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXX XXX X X X XXXXX XXXXXXXXX XXX X X X XXXXXX XXXXXXXX XX
          XXXXXX
           gettext(u'Select a game (optional)') 
        XXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXXBB BBB BBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXBBBBBX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXX X XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXX X X XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX X XXXXXXX XXXX XXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX X X X XXXXXXXXX XXXXX XXXXX X X X XXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X X XXXXXXXXX XXXXXX XXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXX XX
          XXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBB
          XXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXXXX
               gettext(u'Change') 
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXXX
                    XXXXXXX gettext(u'Remove game') XX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX XXX XXXX XXX XX
              XXXXXX
            XXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    
    XXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXBBBBBXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XX
        XXXXXX
         gettext(u'Custom cover')  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'optional') XXXXXXXX
      XXXXXXXXX

      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXBBBBBX
        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
           gettext(u'Upload an image to show instead of the game cover.')   gettext(u'Max 200Kb') 
        XXXX

        
        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXBBBBBXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXX
               XXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
               XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
               gettext(u'Remove current image') 
            XXXXXXXX
          BBBBB
        XXXXXX

        XXXXXX XXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXXXXXXXXXX XXX X XXX XXXXXX XXXXXXX XXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Choose an image') XXXXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX

        BB BBBBBBBBBBBBBBBBBBBBBBBB
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXX
        BBBBB
      XXXXXX
    XXXXXX

    
    XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Players') XXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
        XXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
          
          BB BBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
        XXXXXX
        XXXXX
          XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
          
          BB BBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
        XXXXXX
      XXXXXX
      XX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB

      
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        
        XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Unlimited seats') XXXXXXX
          XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX gettext(u'No seat limit — anyone can join and no empty seats are shown.') XXXXXXX
        XXXXXXXX
      XXXXXX
    XXXXXX

    
    BB BBB BBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
             XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
         gettext(u'Join this table as a player') 
      XXXXXXXX
    XXXXXX
    BBBBB

    
    XXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBB XXXXXXXXXBBBBBXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XX
        XXXXXX
         gettext(u'Extra links')  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'optional') XXXXXXXX
      XXXXXXXXX

      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXBB BBB BBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXBBBBBX
        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
           gettext(u'Add links to useful resources: rulebook, a Google sheet, a video…') 
        XXXX
        
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXX
        BBBBB

        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          BBB BB BB BBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          BBBBBB
        XXXXXX

        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
           gettext(u'Add link') 
        XXXXXXXXX

        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXXXXXX
      XXXXXX
    XXXXXX

    
    XXXX XXXXXXXXXXX XXXXX XXXXXX
      XX XXXXXXBB BBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBX
         XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX X XXXX X XXXXXXXXX XXXXXX XXXXXXXX
         gettext(u'Cancel') 
      XXXX
      XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXX X X X XXXX X X X X X X XX XXX XXXXXXXX
        BB BBBBBBBBBBBBBBBB gettext(u'Save changes') BBBB gettext(u'Publish') BBBBB
      XXXXXXXXX
    XXXXXX

  XXXXXXX

  
  BB BBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
        XXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
           gettext(u'Danger Zone') 
        XXXXXXX
        BB BBBBBBBBBBBB BB BBBBBBBB
          XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX
             XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX X X XXXXXXX XXXXXXXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXX X X XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXX X X X XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X X XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXX X X XXXXX XX XXXXXXXX
             gettext(u'Delete table') 
          XXXX
        BBBB
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
             gettext(u'This table is closed and cannot be deleted.') 
          XXXX
        BBBBB
      XXXXXX
    XXXXXX
  BBBBB

  
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBB

BBBBBBBB BBBBBBB


BBBBB BBBBBBBBBBB
  XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
          XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX
          XXX X X XXXXXXXXXXXXXXXXXX XXXX
          XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX X XXX X XXX
          XX XX XXX XXX X X XX XX X X XX X
          XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXX X XXX X XXXXXXXXXXXXXXXXXXXXX XXXXX
        XXX
      XXX
    XXX

    XX XXXXXX XXX XXXXXXX XXXXXXXX XX XXX XXXXXXXX XXXX XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
      XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXXXXXX

      XX XXXXXXXX XXX XXXXXXXX XXXXXXX XX XX XXX XXXXXXX XX XXXXX XXXXXX
      XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXXXXXX XXXXXXXXXXXXXX X
        XXX XXXX X XXXXXXXXXXXXXXXXX
        XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX X XXX
        XXX XXXXXXXXXXX X XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X
          XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXX XXXX XXX XXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXX XX
          XX XXX XXXXXXXX XXXX XXX XXX XXXXXXXX XXXX XX XXXX XX XXXXXXXXXX
          XXX XXXX X XXXXXXXXXX XXX XXX XX XXXXXXX XX XXXXXXXX XXX XXXXXX
          XX XXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXX X XXXXX
          X
        XXX
        XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX X XXXXXXX X XXX
      X

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX
    XXX

    XX XXXXX X XXXX XXXXXXXX XXXXX XXXXX XXXX XXX XXXXXX XXXXXX XXXXXX XX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
      XXX X X X gettext(u'players') XX
      XX XXXXXXXXXXX XX XXXX XX XXXXXXXXXX XX XXXXX X
        XXXXXX XXXXXXXXXXX XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXX X XXXXXXXXXXX X X X X XX
      X
      XX XXXXXXXXXXX XX XXXXX XXXXXX X gettext(u'up to')  X X XXXXXXXXXX X X X X XX
      XX XXXXXXXXXXX XX XXXXX XXXXXX XXXXXXXXXX X XX X X XX
      XXXXXX XXX
    X
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX X
      XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXX XXXXXXX
      XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXX X XXXXXXXXXXXXXXXXXX X XXXXXXX XXXXXXXXXXXXXXXX X XXX XXXXXXX X
      XXXXXXXXXXXXXXXX X X gettext(u'{game} is designed for {players} — you can still change these numbers.') X
        XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXX XXXXXXXXX XXX
      XXXXXXXXXXXXXXXXXX X XXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX

      XX XXXXXXX XXXXXXX XXXX XXX XXXXXXXX XXXXX XXXX XXXXXXX
      XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XX XXXXXXXXXX XX XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXX
      XX XXXXXXXXX XX XXXXXXXXXX XX XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
    XX
    XXXXXXXXXXXXXXXX X XXXXXXXX XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
      XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX
    XX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
      XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXX X
        XX XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X
          XX XXXXX XXXXXXX
          XXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX
      X
      XX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX X
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
      XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXX XXXXXXX
      XXX XXXX X XXXXXXXXXXXXXXXXXXXX
      XXX XXXXXX X XXXXXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
        XXXXXXXXXXXXXXXXXXX
        XX XXXXXXXX XXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
        XXXXXX X XXXXX
        XXXXXXXXXXXX X XXXXX
        XXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXX X X XXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Publishing...') XX
        XXXXXXXXXXXXXXXXXXXXXXXX
      XXX
    XXX

    XX XX XXXXXX XXXXXX XXXXXXXX X XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
      XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXX XX XXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
          XXX XXXX X XXXXXXXXXXXXXXXXXX XXX XXXXXXX
          XXXXXXXXXXXXXXXXXX X XXXX X XX X XXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXX
      X

      XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XX XXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
          XXX XXXX X XXXXXXXXXXX XX XXXXXXXXXXXXXXX
          XX XXXXXXX XXXXXXX
          XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXX
          XX XXXXXXX X XXX XXXX XXXXXXXXX X XXXXXXX XXXXXXX XXXXXXX XXXXXXX
          XX XXXXXXX XXXXXXXXXXXXX X XXXXXX
        XXX
      X
    XXX

    XX XX XXXXX XXXXXX XXXXXXXX X XXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
      XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXX XX XXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
          XXX XXXX X XXXXXXXXXXXXXXXXXX XXX XXXXXXX
          XXXXXXXXXXXXXXXXXX X XXXX X XX X XXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXX
      X

      XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XX XXXXXXX XX XXXXXXXXX XX XXX XX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
          XXX XXX X XXXXXXXXXXXXXXXXXXXXX XXXX
          XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XXX XXX X XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX X XXX X XX
          XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXX
      X

      XX XXXXXX X XXXX XXXXXXXXX XXXX XXX XXXX XXXXXX XXXX XXXXXX XXXXXXX XXX XXX
      XX XXXXXX XXXXXXX XXXXXX XXXXXXXXX XXXX XXX XXXX XXXXXXX XXXX XXX XXXX
      XX XXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
          XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXX XXXXXXX
          XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXX XXXXXXX
          XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXX XX XXXXXXXXXXXXXX X
            XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXX XXXXXXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
            XXXXXXXXXXXXXXXXX X XXXXXXX
          X XXXX X
            XXXXXXXXXXXXX
          X
        XXX
      X
    XXX
  XXXXXXXXX
BBBBBBBB BBBBBBBBBBB
