BBBB BBBB BBBBBB



XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXX XXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

    
    XXXX XXXXXXXXXXX XXXX XXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
        XXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Add a game') XXXXX
        XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX XXX XXXX XXX XX
          XXXXXX
        XXXXXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

    
    XXXX XXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXX XXX X X X XXXXX XXXXXXXXX XXX X X X XXXXXX XXXXXXXX XX
        XXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'Search for a game...') X
               XXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

    
    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXX

      
      XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXX X XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXX X X XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX X XXXXXXX XXXX XXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX X X X XXXXXXXXX XXXXX XXXXX X X X XXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X X XXXXXXXXX XXXXXX XXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXX XX
        XXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Search among 70.000+ board games') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Type at least 2 characters') XXXX
      XXXXXX

      
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXX
          XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXX X X XXXXXXXXXXXXXXXXXXX
        XXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Searching...') XXXX
      XXXXXX

      
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

    XXXXXX

    
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX XX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX
    XXXXXX

  XXXXXX
XXXXXX

XXXXXXXX
XXXXXXXXX XX X
  XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXX X XXXXX
  XXX XXXXXXXXXXX X XX  XX XXXXXXXXXX XX XXXX XXX XXXXXX XX XXXXXXX XXXXX XXXXXXXXX
  XXX XXXXXXXXXXXXXX X XXX  XX XX X XXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXX XXXXXX XXXXX

  XXXXXXXXXXXXXXXXXXX X XXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
    XXXXXXXXXXXXXXXXXXX XX X XXXXXXXXXXXXXX XX XXXX
  XX
  XXXXXXXXXXXXXXXXXXXX X XXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
    XXXXXXXXXXX X XXX
    XXXXXXXXXXXXXX
    XXXXXXXXXXXX
  XX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
    XX XXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXX
  XXX

  XXXXXXXX XXXXXXXXXXX   X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X

  XXXXXXXX XXXXXXXXX X
    XXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XX X XXXXXXXX X XXX
  X

  XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX X
    XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
  X

  XXXXXXXX XXXXXXXXXX X
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXXXXXX X
    XXXXXX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXXX X XXXXX X XXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXX XXXXXXXXXXX X
    XXX XXXXXXX X XXXX X XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXX X XXXXXXXXX X XXX
    XXX XXXXXX X XXXXX X X XXXXX X XXXXX X XXX X XXX
    XXXXXX XXXXXXXX XXXXXXXXXXXXXX X XXXXXX X X XXXXXXXXXX X XXXXXXX X XX XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXX XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXX
      X XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXXXXX
      X XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXX X XXXXXXX X XXXXXXXXXXXXXX
      X XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      X XXXXXXXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXXXXXX X
    XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      X XXXXXXXXXXXXXX gettext(u'Import from BGG') XX
      X XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXXXXXX
      X XXXXX XXXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXX
      X XXXXXX XXXXXXXXXXXXXXXX gettext(u'Searching BoardGameGeek...') XXXXXXXX
      X XXXXXXXXXXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X
    XXX XXXX X XXX
    XXXXXXXXXXXXXX X XXX
    XX XXXXXXXXXX XX XXXXXXXXXXXXXXXXX X
      XXXX XX XXXXXXXXXXXXXX gettext(u'Already on board-gamers') XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXX XXX X
        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX X XXXX X XX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXX XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXX
    X
    XX XXXXXXXXX X
      XXXX XX XXXXXXXXXXXXXXXXXXXX
    X
    XX XXXXXXX X
      XXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXX X XXXXX
    XXXXXXXXXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X
    XX XXXXXX XXX XXXXXXXXXXXX XXXXXXX  XX XXXXX XXXXXXXXX XXXXXXX
    XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXX XXXXXXX

    XX XXXXXXXXX XX XXXXXXXXXXXXXXXX X
      XX XX XXXX XX XXXXX XXXXXXXX XXXX XXXXX XXXXX
      XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      X XXXX X
        XXXXXXXXXXXXXXXXXXXX
      X
      XXXXXXX
    X

    XXX XXXX X XXXXXXXXXXXXXX gettext(u'Import from BGG') XXX
    XXXX XX XXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX XXX X
      XXXX XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXX X XXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXX XXXXXXXXXX X XXXXXXXXXX
    XXX
    XXXX XX XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX X XXXXX
  X

  XXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXX XXXXXXXXX X
    XXX X X XXXXXXXXXXXXXXXXXXXXXX XX XXX
    XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  XX

  XXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXX X
    XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XX XXXXXX X XXXXXXXXXXXXX X XXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXX XXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
    XX
    XXXXXXXXXXXXXX XXX X XXXXXX XXXXXXXXX XX
    XXXXXXXXXXXXXX XXXXXX X
      XX XXXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
      XXXX X XX XXXXXX X XXXXXXXXXXXXX X XXXXXX X XXXXXXX gettext(u'Import failed. Please try again.') XXX X
    XX
    XXXXXXXXXXXXXXX XX X
      XX XXXXXX X XXXXXXXXXXXXX X XXXXXX X
      XXXXXXX gettext(u'Import failed. Please try again.') XXX
    XXX
  XX

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX X X XXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXX X XX X XXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXXX
    XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XX X
      XXX XXXXX X XXXXXXXXXXXXXX
      XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXX

      XX XXXXX XXXXX XX XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        XXXXXXXXXXXXXX XXX X XXXXXX XXXXXXXXX XX
        XXXXXXXXXXXXXX XXXXXX X
          XX XXXXXX XXX XXXXXXXXXXXX XXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XX
        XXXXXXXXXXXXXXX XX X XX XXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXX

      XX XXXXX XXXXXXXX XXX XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        XXXXXXXXXXXXXX XXX X XXXXXX XXXXXXXXX XX
        XXXXXXXXXXXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX
        XXXXXXXXXXXXXXX XX X XXXXXXXXXXXXXXXXXXXX XXXXXXX XXX
    XX XXXXX
  XXX
XXXXX
XXXXXXXXX
