BBBB BBBBBB
BBBB BBBB BBBBBBBBB
BBBB BBBB
BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXX

XXXXX BBBBBBBBBBBBBBBX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

  XXXX XXX XXX
  BBBBBBB BBBBBBBBBBBBBBBB
  XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBBBBBBBBBXX

  XXXX XXXXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXBBBBBBBBBBBBB BBBBXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXBBBBBBBBBBBBB BBBBXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXBBBBBBBBBBBBB BBBBXX

  XXXX XXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX

  XXXX XXX XXX
  XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

  XXXX XXXXXXXX XXXX XXX XXXXXXXXXX XXXXXXX X XX XXXXXXXXXX XXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
    XXXXXXXXXXXXXXX X X
      XXXXXX X
        XXXXXXX X
          XXXXXXXXXXX X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XX
          XXXXXXX X
            XXXXXXXX  X XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XX
            XXXXXX    X XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XX
            XXXXXXX   XXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXX
            XXXXXXXX  X XXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XX
            XXXXXXX   XXXXXXXXXX
          XX
          XXXXXXXXXX X
            XXXXX XX XXX XXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XX XXX XXXX XXXXXXXXXXXXXXXXX
          XX
        X
      X
    X
  XXXXXXXXX

  XXXXXXX
    XXXX X XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX X
    XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXX X
    XXXXXXXXX X XXXXXXXXXX XXXXXXXXX X
    XXXXXXXXX XX X XXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXX XX X
    XXXXXXXXX XX X XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXX XX X
    XXXXXXXXX X X XXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXX XX X
    XX XXXXXXX X XXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXX XXXXXXXX XX
    XXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXX X
    XX XXXXXX XXXXXX XXXXX X XXXXXXX XXXXXXX XXXXX XXX XXXX X XXXXXXXXXX XXXXXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXX X XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX
      XXXXXXXXXXXXXXXX XXXXXX XXXXXXX
      XXXXXXXXXXXXXX XXXXXXX
    X
  XXXXXXXX

  BBBBB BBBBBBBBBBBBB BBBBB

  XXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  X
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX XXXXXX XXXXXXXX
    XXXXXX XXXXXXX
    XXXXXXX XXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X
  XXXXXXXXX
  BBBBB BBBBBBBBBBBBBB BBBBBB

  XXXX XXXXXX XXX XXXXXXX XXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXX XXXXXX XXX XXXXXXX XXX
XXXXXXX

XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX

XXXX XXXXXX XXX XXXXXXX XXXXXXXXXX XXX
XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX XXX XXXXXX XXX XXXXXXX XXXXXXXXXX XXX

BBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBB
BBBBB BBBBBBBBBBBBBB BBBBBB

XXXXXXX
XXXXXXX
