BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX

  
  XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX
    XX XXXXXXBBB BBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Games') XXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXX

  
  XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXX
       XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
      BBBBB
    XXXXXX
  XXXXXX

  
  XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXX XX
        XXXXXX
      XXXXXX
      XXXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Played tables') XXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX X X X XXXXXXXXX XXXXX XXXXX X X X XXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXXXXX XXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXX XX
        XXXXXX
      XXXXXX
      XXXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Gamers') XXXX
      XXXXXX
    XXXXXX
    BB BBBBBBBBBBBBB
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
         XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXX X X X X XXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXXXXX XXXX XXX XXXXXXXXXX XXXXXXX XX
        XXXXXX
         gettext(u'View on BoardGameGeek') 
      XXXX
    BBBBB
  XXXXXX

  
  BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXX
    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Game info') XXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXX

      BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX X X X XXXXXXXXX XXXXX XXXXX X X X XXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXXXXX XXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXX XX
          XXXXXX
        XXXXXX
        XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Players') XXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBB
              BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBXBBBBB
            BBBB BBBBBBBBBBBBBBBBX
            BBBBX
            BBBBB
          XXXX
        XXXXXX
      XXXXXX
      BBBBB

      BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXX X X X XXXX X X X X X X XX XXX XX
          XXXXXX
        XXXXXX
        XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Playtime') XXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBB
              BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB XXXBBBBX XXXBBBBB
            BBBB BBBBBBBBBBBBBBBBBX XXX
            BBBBX XXX
            BBBBB
          XXXX
        XXXXXX
      XXXXXX
      BBBBB

      BB BBBBBBBBBBB
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX X X X XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX X XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX X XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX
          XXXXXX
        XXXXXX
        XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Complexity') XXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBB B BBB
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Light') XXXX
            BBBB BBBBBBBBBBB B BBB
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Medium') XXXX
            BBBB
              XX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Heavy') XXXX
            BBBBB
          XXXXXX
        XXXXXX
      XXXXXX
      BBBBB

    XXXXXX
  XXXXXX
  BBBBB

  
  BB BBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
    XXXXXX
  BBBBB

  
  BB BBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXX XXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Played at') XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      BBB BBBBBBBB BB BBBBBBBBB
      XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX
         XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
        BB BBBBBBBBBBBBBB
          XXXX XXXXXX XXXXXX
               XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
        BBBB
          XXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X X X XXX X X X X X X X XXX XX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXX XXXXXXXX XXX X X X XX XXX XX
            XXXXXX
          XXXXXX
        BBBBB
        XXXX XXXXXXXXXXXXX XXXXXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXBBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'tables') XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XX
        XXXXXX
      XXXX
      BBBBBB
    XXXXXX
  XXXXXX
  BBBBB

XXXXXX
BBBBBBBB BBBBBBB
