BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Account') XXXX X
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Notifications') XXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Notification preferences') XXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Enable or disable notifications for the following activities.') XXXX
  XXXXXX

  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    BBBBBBBBBB

    
    XXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Push notifications') XXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Sent directly to your browser or device, even when the app is in the background.') XXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXX

      
      XXXXXX XXXXXX
             XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'New table') XXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'A new table is created in a location you follow') XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX
                 XXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXX XXXXX
                 BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
          XXXX XXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                      XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXXXX

      
      XXXXXX XXXXXX
             XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'New player') XXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'A new player joins a table you created') XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX
                 XXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXX XXXXX
                 BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
          XXXX XXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                      XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXXXX

    XXXXXX

    
    XXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Email notifications') XXXXX

    BB BBB BBBBBBBBB
    XXXX XXXXXXXXXXX XXXXX XXX XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXX
         gettext(u'To enable email notifications you must first add a valid email to your account.') 
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Add email') XXXX
      XXXXXXX
    XXXXXX
    BBBB
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Sent to your email address.') XXXX
    BBBBB

    XXXXXXXXX BB BBB BBBBBBBBBXXXXXXXXBBBBBX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXX BB BBB BBBBBBBBBXXXXXXXXXXBBBBBXX

      
      XXXXXX XXXXXX
             XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXX BB BBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXXX
        XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'New table') XXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'A new table is created in a location you follow') XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX
                 XXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXX XXXXX
                 BB BBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
          XXXX XXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                      XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXXXX

      
      XXXXXX XXXXXX
             XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXX BB BBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXXX
        XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'New player') XXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'A new player joins a table you created') XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX
                 XXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXX XXXXX
                 BB BBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
          XXXX XXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                      XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXXXX

      
      XXXXXX XXXXXX
             XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXX BB BBBBBBBBBXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXXX
        XXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'New comment') XXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u"A new comment is written in a table you're participating in") XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX
                 XXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXX XXXXX
                 BB BBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXBBBBBX
          XXXX XXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                      XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXXXX

    XXXXXX
    XXXXXXXXXXX

    XXXX XXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX X X XXXXXXX XXXXXXXX
         gettext(u'Save preferences') 
      XXXXXXXXX
    XXXXXX

  XXXXXXX

BBBBBBBB BBBBBBB
