BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Account') XXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'My memberships') XXXXX
  XXXXXX

  
  BB BBBBBBBBBBBBBBBBBB
    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Active memberships') XXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXX
      BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
           XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXX XXXXXX
               XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBB BB BBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Pending') XXXXXXX
              BBBB
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Active') XXXXXXX
              BBBBB
              BB BBBBBBBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
              BBBBB
            XXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBB
                FFFFFFFFFFFF X FFFFFFFFFFFF
              BBBB BBBBBBBBBBBBBBBBBBBBB
                 gettext(u'From')  FFFFFFFFFFFF
              BBBBB
            XXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XX
          XXXXXX
        XXXX
      BBBBBB
    XXXXXX
  BBBB
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
      XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXXXXXX XXXX X X X XXX XXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXX XXXXX XXXXX X X X XXXXX XXX XX
        XXXXXX
      XXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'No active memberships') XXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Some locations manage memberships on board-gamers. In questo momento non hai membership attive.') XXXX
    XXXXXX
  BBBBB

  
  BB BBBBBBBBBBBBBBBB
    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Expired memberships') XXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
           XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XXXX XXXXXX XXXXXX
               XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBB BB BBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Expired') XXXXXXX
              BBBB
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Rejected') XXXXXXX
              BBBBB
              BB BBBBBBBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
              BBBBB
            XXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBB
                FFFFFFFFFFFF X FFFFFFFFFFFF
              BBBB BBBBBBBBBBBBBBBBBBB
                 gettext(u'Until')  FFFFFFFFFFFF
              BBBBB
            XXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XX
          XXXXXX
        XXXX
      BBBBBB
    XXXXXX
  BBBBB

BBBBBBBB BBBBBBB
