BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Account') XXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'My tables') XXXXX
  XXXXXX

  BB BBB BBBBBBBBBBBBB BBB BBB BBBBBBBBBBB
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXX
      XXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'No tables yet') XXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Join or create a table to get started.') XXXX
    XXXXXX
  BBBB

    
    BB BBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXX XXXXXXX
        BBB BBBBB BB BBBBBBBBBBBBB
          BBBBBBBBBBBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBBB
        BBBBBB
      XXXXXX
    BBBB
      XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXX
        XXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'No upcoming tables.') XXXX
      XXXXXX
    BBBBB

    
    BB BBBBBBBBBBB
      XXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Past tables') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
        BBB BBBBB BB BBBBBBBBBBB
          BBBBBBBBBBBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBBB
        BBBBBB
      XXXXXX
    BBBBB

  BBBBB

XXXXXX
BBBBBBBB BBBBBBB
