BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  
  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Edit profile') XXXXX
  XXXXXX

  
  XXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXX XXXXXX XXXXXX
           XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX gettext(u'Change avatar') X
              XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXX X X X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXX XXXX XXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X X XXXXXXXXXXXX XXXX XXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXX XXXXXX XXXXXX X X XXXXXXX X XXXXX XXXXX X X XXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXX X X XXX X XXX XXX X X X X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXXXX
    XXXXXX
  XXXXXX

  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB

    
    
    
    

    
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
      XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
          
        XXXXXXXX
        
        BB BBBBBBBBBBBBBBBBBBBBBB
          XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXX
        BBBBB
      XXXXXX
      XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
          
        XXXXXXXX
        
        BB BBBBBBBBBBBBBBBBBBBBB
          XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXX
        BBBBB
      XXXXXX
    XXXXXX

    
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
      
      XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
        
      XXXXXXXX
    XXXXXX

    
    XXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
        
      XXXXXXXX
      
      BB BBBBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXX
      BBBBB
    XXXXXX

    
    XXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
         XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXX
      XXXXXXXX
      
      BB BBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXX
      BBBBB
    XXXXXX

    
    XXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
        
      XXXXXXXX
      
      BB BBBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXX
      BBBBB
    XXXXXX

    
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

    
    XXXX XXXXXXXXXXX XXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBX
         XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX X XXXX X XXXXXXXXX XXXXXX XXXXXXXX
         gettext(u'Cancel') 
      XXXX
      XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX X X XXXXXXX XXXXXXXX
         gettext(u'Update profile') 
      XXXXXXXXX
    XXXXXX

  XXXXXXX

  
  XXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Change email') XXXXX
    BB BBBBBBBBBBBBBBB BB BBBBBBBBBB
      XXXX XXXXXXXXXXX XXXXX XXX XXXX XXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX X X X XXXXXXXXXXXXXXX XXXXXXXXXXXX X X X XXXXXXXXXXXXXXXXXXXXXX XXXX X X X XXXX X X X X X X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX gettext(u'Your account is linked to Telegram and has no email address. You can add one below.') XXXXXXX
      XXXXXX
    BBBBB
    XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX
      BBBBBBBBBB
      BB BBBBBBBBBBBBBBBBBB
      XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
           gettext(u'Current email') 
        XXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXX
      BBBBB
      XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBB gettext(u'New email') BBBB gettext(u'Email address') BBBBB
        XXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
               XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'New email address') XX
      XXXXXX
      BB BBBBBBBBBBBBBBBBBBB
      XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Current password') 
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
               XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXX gettext(u'Confirm with your password') XX
      XXXXXX
      BBBBB
      XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBB gettext(u'Update email') BBBB gettext(u'Add email') BBBBB
      XXXXXXXXX
    XXXXXXX
  XXXXXX

  
  XXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Connected accounts') XXXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX

      
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
          XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXX XXX X X X XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXX XXXXXX X XXXXXX XXXXXXXXXXXXXXXX XXX X X XXXXXXXXXXXXXX X X X X X XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXX XXXXXXXX XXX X X X XXXXXXXXXXX X X X X X XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXX XXXXXXX X XXXXX XXX XXXXXX XXXXX X X X X X XXX XXXXXXX XXX X X X XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX
          XXXXXX
          XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Connected') XXXX
            BBBB
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Not connected') XXXX
            BBBBB
          XXXXXX
        XXXXXX
        XXXXX
          BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBBBBBBBB
              XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBXX
                BBBBBBBBBB
                XXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                   gettext(u'Disconnect') 
                XXXXXXXXX
              XXXXXXX
            BBBB
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXX gettext(u'Set a password and email, or connect another account first') XX
                 gettext(u'Disconnect') 
              XXXXXXX
            BBBBB
          BBBB
            XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBX
               XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXX X X X XXXXX XXXXXXXXXX XXXXXXX XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX X X XXXXXXXXXXXXXXXXXX XXXXXXX XXX X X X XXXXX XXXXXX XXXXXXXX
               gettext(u'Connect') 
            XXXX
          BBBBB
        XXXXXX
      XXXXXX

      
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXX XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
          XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXX XXXXXXX X X XXXXX X XXXXXXXX XX XX XX XXXXXXXX XXXXXXXXXXXX X XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXXX
          XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Connected') XXXX
            BBBB
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Not connected') XXXX
            BBBBB
          XXXXXX
        XXXXXX
        XXXXX
          BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBB
              XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBXX
                BBBBBBBBBB
                XXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                   gettext(u'Disconnect') 
                XXXXXXXXX
              XXXXXXX
            BBBB
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXX gettext(u'Set a password and email, or connect another account first') XX
                 gettext(u'Disconnect') 
              XXXXXXX
            BBBBB
          BBBB BBBBBBBBBBBBBBBBBBBB
            XX XXXXXXX
               XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXX X X X XXXXX XXXXXXXXXX XXXXXXX XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX X X XXXXXXXXXXXXXXXXXX XXXXXXX XXX X X X XXXXX XXXXXX XXXXXXXX
               gettext(u'Connect') 
            XXXX
          BBBBB
        XXXXXX
      XXXXXX

    XXXXXX
  XXXXXX

BBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB
