BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  
  XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXX XXXXXX
           XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    BBBB
      XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
      XXXXXX
    BBBBB
    XXXX XXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBX
         XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'See public profile')  XXXXX
    XXXXXX
  XXXXXX

  
  XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX

    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX
       XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXX X X XXXXX X XXXX XXXX X X X XXX XXXXXXXX XXXXXXXXXX XXX X X X XXXXXX XXXXXXXX XXXXXX X X X XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Edit profile') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Edit your personal and account information') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XXXXXXXX
    XXXX

    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX
       XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X X X XXX X X X X X X X XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXX XXXXXXXX XXX X X X XX XXX XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Manage locations') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Edit the information of your locations and create new ones') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XXXXXXXX
    XXXX

    XX XXXXXXBBB BBBBBBBBBBBBBBBBX
       XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Manage tables') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Edit the information of the tables you organized') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XXXXXXXX
    XXXX

    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX
       XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXX XX XX XXXXXXX XXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXXX XXXXX XXXXX XXXXX X X XXXXXXX XXXXXXXXXXX XXXXX X X X XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXXXXXX XXXXX X X X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXX XXXXX XXXXX X X X XXXXXXXXXXXXXXXXX XXXXX X X X XX XXXXXXX X XXXXXXX XXXXX XXXXXXXXXXX XXXXX X X X XXXXX XXXXX XXXXX XXXXX X X X XXXXX XXXXXXXXXXX XXXXX X X X XX XXXX XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'My memberships') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX gettext(u'View your active and past memberships at locations') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XXXXXXXX
    XXXX

    XX XXXXXXBBB BBBBBBBBBBBBBBBBBX
       XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXX X X XXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXXXXXX XXXX X X X XXXX XXXXXX XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Change password') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Update your login password') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XXXXXXXX
    XXXX

    XX XXXXXXBBB BBBBBBBBBBBBBBBBX
       XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX X X X XXXXXXXXXX X X X X XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X X X XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X X XXXXXXXXX XXXXXXX XXXXX X X XXXXXXXXXXXXXX XXXXXXX XXXXX X X X XX XXXXXXXXXXX XXXXX X X XXXXXXX XXXXXXX XXX X X X XXXXXXX XXXX XXXXX XXXXX X X X XXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXX XXXXXXXX XXXXXX X X X XXX X X X X X X X XXXX XXXXXX XXXX X X XXXXX X XXXX XXXX X X X XXX XXXXXXXX XXXXXX XXXX X X XXXXX X XXXX XXXX X X X XXX XXX XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'My guests') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Manage the guest identities you can bring to tables') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XXXXXXXX
    XXXX

    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XX XXXXXXBBB BBBBBBBBBBBBBBBBX
       XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X X XX XXXXXXXXXX XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Events') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Manage the events you created or coordinate') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XXXXXXXX
    XXXX
    BBBBB

    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX
       XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX X X X XXXXXXXXXXXXXXXX XXXXX X X X XX XXXXXXXX X X X X X XXXXXXXXXXX XXXXX X X XXXXXXX XXXXXXXXXXXXXX XXXX XXXXX XXXXX XXXXXXXXXX XXXXXXXX XXXXXX X X XXXXXXX XXXXXXX XXX X X X XXXXXXX XX XXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Notification preferences') XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Choose notification preferences and how you want to be contacted') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXX XXXX XXXXXXXX
    XXXX

  XXXXXX

BBBBBBBB BBBBBBB
