BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
    XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Account') XXXX X
      XXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Events') XXXXX
    XXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBX
       XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
       gettext(u'Create event') 
    XXXX
  XXXXXX

  BB BBBBBBBBBBBB BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX

    BB BBBBBBBBBBBB BB BBBBBBBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Organized by you') XXXXX

      BBB BBBBB BB BBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX
           XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBB
            XXXX XXXXXX XXXXXX
                 XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
          BBBB
            XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X X XX XXXXXXXXXX XXXXXXXX
            XXXXXX
          BBBBB
          XXXX XXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX
              XXXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
          XXXXXX
          BB BBBBBBBBBBBB BB BBBBBBBBBB
            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Approved') XXXXXXX
          BBBB BBBBBBBBBBBB BB BBBBBBBBB
            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Pending') XXXXXXX
          BBBB
            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Rejected') XXXXXXX
          BBBBB
        XXXX
      BBBBBB

      BBB BBBBB BB BBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX
           XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBB
            XXXX XXXXXX XXXXXX
                 XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
          BBBB
            XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X X XX XXXXXXXXXX XXXXXXXX
            XXXXXX
          BBBBB
          XXXX XXXXXXXXXXXXX XXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
          XXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Manager') XXXXXXX
        XXXX
      BBBBBB
    XXXXXXXXXX
    BBBBB

    BB BBBBBBBBBBBBBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u"Events you're attending") XXXXX

      BBB BBBBB BB BBBBBBBBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX
           XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBB
            XXXX XXXXXX XXXXXX
                 XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
          BBBB
            XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X X XX XXXXXXXXXX XXXXXXXX
            XXXXXX
          BBBBB
          XXXX XXXXXXXXXXXXX XXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
          XXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Attending') XXXXXXX
        XXXX
      BBBBBB
    XXXXXXXXXX
    BBBBB

    XXXXXX

  BBBB
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X X XX XXXXXXXXXX XXXXXXXX
      XXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'No events yet') XXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX gettext(u'Create a GamesCon-style event and manage tables and play areas.') XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBX
         XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
         gettext(u'Create event') 
      XXXX
    XXXXXX
  BBBBB

BBBBBBBB BBBBBBB
