BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXX

  XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXX
      XXXXX XXXXXX XXXXXXX X X XXXXX X XXXXXXXX XX XX XX XXXXXXXX XXXXXXXXXXXX X XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX

  XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Link Telegram account') XXXXX
  XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX gettext(u'Click the button below to link your Telegram account.') XXXX

  BB BBBBBBBBBBBBBBBBBBBB
    XX XXXXXXX XXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX X X XXXXX X XXXXXXXX XX XX XX XXXXXXXX XXXXXXXXXXXX X XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Link Telegram') 
    XXXX
  BBBB
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Telegram login is not configured.') XXXX
  BBBBB

  XXXX XXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
       gettext(u'Cancel') 
    XXXX
  XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBB
XXXXXXXX
  XX XXXXXXXX XXXXXXX XXX XXXXXXXX XXXXXXX XXXX XXXXX XX XXXXXXXXXXXXXX
  XXXXXXXXX XX X
    XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXX XXXXXXX
    XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXX XXXXXXXXXXXXXXXXX X X gettext(u'Linking account...') XX
    XX XXXXX XXXXXXXXXXXXXXX X X gettext(u'Please wait.') XX
    XX XXXXX XXXXXXXXXXXXXXXXX X XXXXXXX
    XXX X
      XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBXX X XXXXXXXXXXXXXXXXXXX
    X XXXXX XXX X
      XX XXXXX XXXXXXXXXXXXXXX X X gettext(u'An error occurred. Please try again.') XX
    X
  XXXXX
XXXXXXXXX
BBBBBBBB
