BBBB BBBB

XXXXXXXXX
  XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
    XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXX X X X X X XXXXXXX X X X X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXX XX XXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXX XXXXX XXXXX X X XXXXXXX XXXXXXX XXXXXXX XXXXX X X XXXXXXX XXXXXX XXXXXXX XXXXX X X XXXXXXX XX XXXXXXXX
       gettext(u'Leaderboard') 
      BB BBBBBBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          
        XXXXXXX
      BBBBB
    XXXXX
    BB BBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBB
      XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXX XXXXXXXXX XXX X X XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXX X X X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXX X X X XXXXX XXXXXXXXXXXX XXXX X X X X XXXXXXXXXXXXXXX XXXX X X X XXXX XXXXX XXXXXXXX
         gettext(u'Edit') 
      XXXXXXXXX
    BBBBB
  XXXXXX

  BB BBB BBBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'Not enabled for this game.') XXXX
  BBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Use the') 
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
       gettext(u'to adjust the positions') X
    XXXXXXXX

    BB BBBBBBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBB
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'Create Leaderboard') 
      XXXXXXXXX
    BBBB BBB BBBBBBBBBBBBBBBBBBB
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'Leaderboard not created yet.') XXXX
    BBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX BB BBB BBBBBBBBBBBBBBBBBBBXXXXXXBBBBBXX
      BBB BBBBBB BB BBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
            XXXXXXX
          BBBBB
          XXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBB BB BB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'NEW') XXXXXXX
          BBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          BBBBB
        XXXXXX
      BBBBBB
    XXXXXX

    BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
      XXXXXXX XXXXXXXXXXXXXX
              XXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXX
         gettext(u'Update Leaderboard') 
      XXXXXXXXX
    BBBBB
  BBBBB
XXXXXXXXXX
