BBBB BBBB
 #
 #
 #
 #

XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
  
  XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
           gettext(u'Label')  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'optional') XXXXXXXX
        XXXXXXXX
        
        BB BBBBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
      XXXXXX
      XXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX
           gettext(u'URL') 
        XXXXXXXX
        
        BB BBBBBBBBBBBBBXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXFFFFFFF FXXXXBBBBB
      XXXXXX
    XXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXX gettext(u'Remove link') XX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX XXX XXXX XXX XX
      XXXXXX
    XXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXX
