BBBB BBBB

XXXXXXXXX
  XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX
     gettext(u'Participants')  XBB BBB BBBBBBBBBBBBBBBBBBBBBXBBBBBX
  XXXXX
  XXXX XXXXXXXXXXXXXXXXXX

    BBB BBBBBBBBBB BB BBBBBBB
      BB BBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFF
          XXXXXX
          XXXX XXXXXXXXXXXXX XXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'guest of')  XXXX
          XXXXXX
          BB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB
              XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBXX
                BBBBBBBBBB
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Remove guest') XX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXX XXXXXX X X X XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                XXXXXXXXX
              XXXXXXX
            BBBBB
          BBBBB
        XXXXXX
      BBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX
             XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXX XXXXXX
                   XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXBBBBBXX
            BBBB
              XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX
                          BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXXXX XXXXXXXXXXXXX
                          BBBBXXXXXXXXXXXX XXXXXXXXXXXXXXBBBBBXX
                FFFFFFFFFFFFFFF
              XXXXXX
            BBBBB
            XXXX XXXXXXXXXXXXX XXXXXXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX
                
                BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX X X X XXXX XXXXXXX XXXXXXXXXXXXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXX XXXXXXX XXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X X XXXXXXXXXXXXXXX XXXXX XXXXXXXX
                BBBBB
              XXXX
            XXXXXX
          XXXX
          BB BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
               XXXXXXX gettext(u'Call')  XX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXX XX XX XXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXX XXXXXXXX
            XXXX
          BBBBB
        XXXXXX
      BBBBB
    BBBBBB

    
    BB BBBBBBBBBBBBBBBBBBBBB BB BBB BBBB
      XXXX XXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
              BBB B BB BBBBBBBBBBBBBBBBBBBBB
                XXXXXXX XXXXXXXXXXXXXXXXXX
              BBBBBB
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
               gettext(u'Add guest') 
            XXXXXXXXX
          XXXXXXX
        BBBB
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
             gettext(u'All your guests are already at the table.') 
            XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Manage guests') XXXX
          XXXX
        BBBBB
      XXXXXX
    BBBBB

    BB BBBBBBBBBBBBBBBBBBBBBB B B
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXX X X XXXXX X XXXX XXXX X X X XXX XXXXXXXX XXXXXXXXXX XXX X X X XXXXXX XXXXXXXX XXXXXX X X X XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          
          BB BBBBBBBBBBBBBBBBBBBBBB BB B gettext(u'external gamer') BBBB gettext(u'external gamers') BBBBB
        XXXX
      XXXXXX
    BBBBB

    BB BBBBBBBBBBBBBBB B B BBB BBB BBBBBBBBBBBBBBBBBBBBB
      BBB B BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
          XXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Open seat') XXXX
        XXXXXX
      BBBBBB
    BBBBB

  XXXXXX
XXXXXXXXXX
