BBBB BBBB

XXXXXXXXX
  XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Comments') XXXXX

  BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
      BBBBBBBBBB
      XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
                XXXXXXXXXXXXX gettext(u'Write a comment...') X
                XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XXXXX XXXXXXXXXXXX XXXXXX X X X XXXXXX XX XXXXXX XXXXXX X X X XXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX
         gettext(u'Send comment') 
      XXXXXXXXX
    XXXXXXX
  BBBB
    XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX X X X XXXX X X X X X X XX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
       gettext(u'Only gamers that joined the table can comment on this page.') 
    XXXXXX
  BBBBB

  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
    BBB BBBBBBB BB BBBBBBBBBBBBBBBBBB
      BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXX
            BB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB gettext(u'%(nickname)s joined the table') SSSSSSSSSSSS SSSSSS SSS SSSSSBBBBBBB
            BBBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB gettext(u'%(nickname)s left the table') SSSSSSSSSSSS SSSS SSS SSSSSBBBBBBB
            BBBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB gettext(u'%(nickname)s added to the table') SSSSSSSSSSSS SSSSS SS SSS SSSSSBBBBBBB
            BBBB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB gettext(u'%(nickname)s removed from the table') SSSSSSSSSSSS SSSSSSS SSSS SSS SSSSSBBBBBBB
            BBBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB gettext(u'%(name)s (guest) joined the table') SSSSSSSS SSSSSSS SSSSSS SSS SSSSSBBBBBBB
            BBBB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB gettext(u'%(name)s (guest) left the table') SSSSSSSS SSSSSSS SSSS SSS SSSSSBBBBBBB
            BBBBB
            X FFFFFFF F FFFF
          XXXXXXX
          XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX
      BBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX FFFFFFF F F FFFFXXXXXXX
            XXXXXX
            BB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
              XXXXXXX XXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBXXX
                      XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX X X XXXXXXX XXXXXXXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXX X X XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXX X X X XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X X XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXX X X XXXXX XX XXXXXXXX
              XXXXXXXXX
            BBBBB
          XXXXXX
          XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX
      BBBBB
    BBBBB
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXX gettext(u'There are no comments yet.') XXXX
    BBBBBB
  XXXXXX
XXXXXXXXXX


XXXX XXXXXXXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX
     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Confirm delete') XXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Are you sure you want to delete the comment?') XXXX
    XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
         gettext(u'Cancel') 
      XXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
           gettext(u'Delete') 
        XXXXXXXXX
      XXXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X
  XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X
XXXXXXXXX
