BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB BBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX

  
  XXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Upcoming Tables') XXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Accept the challenge, join a table!') XXXX
  XXXXXX

  
  BB BBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXX
      BBB BBBBB BB BBBBBBBBBBBBB
        BBBBBBBBBBBBBBBBBBBBB BBBBB
      BBBBBB
    XXXXXX
  BBBB
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXX
      XXXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'No upcoming tables.') XXXX
    XXXXXX
  BBBBB

  
  BB BBBBBBBBBBB
    XXXX XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX gettext(u'Past tables') XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
      BBB BBBBB BB BBBBBBBBBBB
        BBBBBBBBBBBBBBBBBBBBB BBBBB
      BBBBBB
    XXXXXX
  BBBBB

XXXXXX
BBBBBBBB BBBBBBB
