BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBBB

BBBBB BBBBBBB

  
  BB BBBBBBBBBBBBBB
  XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBX
     XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX X XXXX X XXXXXXXXX XXXXXX XXXXXXXX
    
  XXXX
  BBBB
  XX XXXXXXBBB BBBBBBBBBBBBBX
     XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX X XXXX X XXXXXXXXX XXXXXX XXXXXXXX
     gettext(u'Back to tables') 
  XXXX
  BBBBB

  
  XXXX XXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXX
    XXXX XXXXXX XXXXXX
         XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXX XXXXXXXXXXXX
                 BB BBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXX
                 BBBB BBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXXXXXX XXXXXXXXXX
                 BBBBXXXXXXXXXXXX XXXXXXXXXXBBBBBXX
      
    XXXXXXX
  XXXXXX

  
  XXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
    BB BBBBBBBBBB
      XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    BBBBB
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Created')  FFFFFFFFF  gettext(u'ago') XXXX
  XXXXXX

  
  XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX

    
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

      
      BB BBBBBBBBBBBBBBBBB
        XXXXXXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Description') XXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBB B BBB
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                      XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                      XXXXXXXXXXXXXXX X XXXXXXXX X X gettext(u'Read more') X X X gettext(u'Show less') XX
                    X
                    XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
               gettext(u'Read more') 
            XXXXXXXXX
          BBBB
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXXX
          BBBBB
        XXXXXXXXXX
      BBBBB

      
      BB BBBBBBBBBBBBBBB
        XXXXXXXXX
          XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Useful links') XXXXX
          XXX XXXXXXXXXXXXXXXXXXXX
            BBB BBBB BB BBBBBBBBBBBBBBB
              XXXX
                XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXX X X X XXXXX XXXXXXXXXX XXXXXXX XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX X X XXXXXXXXXXXXXXXXXX XXXXXXX XXX X X X XXXXX XXXXXX XX
                  XXXXXX
                  XXXXXXXXXXXXX
                XXXX
              XXXXX
            BBBBBB
          XXXXX
        XXXXXXXXXX
      BBBBB

      
      XXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X X XX XXXXXXXXXX XXXXXXXX
          XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Date') XXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFF F F FFXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXX X X X XXXX X X X X X X XX XXX XXXXXXXX
          XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Time') XXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFFFXXXX
          XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX X X X XXXXXXXXX XXXXX XXXXX X X X XXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXXXXX XXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXX XXXXXXXX
          XXXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Seats') XXXX
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBB
                 XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Unlimited seats') XXXXXXX
              BBBB
                X
                BB BBBBBBBBBBBBBBB B B
                  XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'free') XXXXXXXX
                BBBBB
              BBBBB
            XXXX
          XXXXXX
        XXXXXX

        BB BBBBBBBBBBBBBB
          XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXX XXXXXXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X X X XXX X X X X X X X XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXX XXXXXXXX XXX X X X XX XXX XXXXXXXX
            XXXX XXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Location') XXXX
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB gettext(u'Private location') BBBBB
              XXXX
            XXXXXX
          XXXXXX
        BBBBB

      XXXXXXXXXX

      
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

      
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

      
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    XXXXXX

    
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX

        
        XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXX XXXXXX
               XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXX XXXXXXXXXXXX
                       BB BBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXX
                       BBBB BBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXXXXXX XXXXXXXXXX
                       BBBBXXXXXXXXXXXX XXXXXXXXXXBBBBBXX
            
          XXXXXXX
        XXXXXX

        
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXX

          
          XXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX X X X XXXXXXXXX XXXXX XXXXX X X X XXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXXXXX XXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXX XXXXXXXX
                 gettext(u'Unlimited seats') 
              XXXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX  gettext(u'players') XXXX
            BBBB
              XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXX
                XXXXXX  gettext(u'players') XXXXXXX
                XXXXXX  gettext(u'max') XXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
                BB BBBBBBBBBBBBBBB B B
                    gettext(u'available seats') 
                BBBB
                   gettext(u'Table is full') 
                BBBBB
              XXXX
            BBBBB
          XXXXXX

          
          BB BBBBBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBBBBBBBB
              BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBXX
                  BBBBBBBBBB
                  XXXXXXX XXXXXXXXXXXXX
                          XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXX XXXXXX X X X XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                     gettext(u'Leave this Table') 
                  XXXXXXXXX
                XXXXXXX
              BBBB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                   gettext(u'Table reserved for members') 
                XXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  BB BBBBBBBBBBBBBBBBBBBBBB
                    XXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXX X X X XXXX X X X X X X XX XXX XXXXXXXX
                       gettext(u'Membership pending') 
                    XXXXXXX
                  BBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBX
                       XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                       gettext(u'Become a member') 
                    XXXX
                  BBBBB
                BBBBB
              BBBB
                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBB BBBBBBBBBBXX
                  BBBBBBBBBB
                  XXXXXXX XXXXXXXXXXXXX
                          BB BBB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBB BB BXXXXXXXXBBBBB
                          XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                    BB BBB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBB BB B gettext(u'Table is full') BBBB gettext(u'Join this table') BBBBB
                  XXXXXXXXX
                XXXXXXX
              BBBBB
            BBBB
              XX XXXXXXBBB BBBBBBBXXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBX
                 XXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                 gettext(u'Login to join table') 
              XXXX
            BBBBB
          BBBB
            XXXXXXX XXXXXXXX
                    XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
               gettext(u'This table is closed') 
            XXXXXXXXX
          BBBBB

          
          XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
             XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
             gettext(u'Add to Google Calendar') 
          XXXX

          
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Link copied!') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX X XX XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX X X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXX XXXXXX XXXX X X X XXXXX XXXXX XXXX XXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXX XXXX XXXX X X XXXXXXX XXXXXXXX XXXXXXXX  gettext(u'Share') XXXXXXXXXX
                  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXX X X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXX XXXXXX XXXX X X X XXXXX XXXXX XXXX XXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXX XXXX XXXX X X XXXXXXX XXXXXXX XXXXXXXX
             gettext(u'Share') 
          XXXXXXXXX

          
          BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX
              BB BBBBBBBBBBBB BB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBX
                   XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXX XXXXXXXXX XXX X X XXXXXXX XXXXXX XXXXXXXXXXXXXXX XXX X X X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXX X X X XXXXX XXXXXXXXXXXX XXXX X X X X XXXXXXXXXXXXXXX XXXX X X X XXXX XXXXX XXXXXXXX
                   gettext(u'Edit table info') 
                XXXX
              BBBBB
              XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBX
                 XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX X X X XXXXXXXXX XXXXX XXXXX X X X XXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXXXXX XXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXX XXXXXXXX
                 gettext(u'Invite/Remove Gamers') 
              XXXX
            XXXXXX
          BBBBB

        XXXXXX

        
        BB BBBBBBBBBBBBBB
          XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBX
             XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXX XXXXXX XXXXXX
                   XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X X X XXX X X X X X X X XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXX XXXXXXXX XXX X X X XX XXX XXXXXXXX
                  
                XXXX
              BBBBB
            XXXXXX
          XXXX
        BBBBB

      XXXXXX
    XXXXXX

  XXXXXX

  
  XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBB
      BB BBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXX XXXXXX X X X XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
               gettext(u'Leave this Table') 
            XXXXXXXXX
          XXXXXXX
        BBBB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
               gettext(u'Table reserved for members') 
            XXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBBB
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBX
                 XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Become a member') 
              XXXX
            BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBB
              XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                 gettext(u'Membership pending') 
              XXXXXXX
            BBBBB
          XXXXXX
        BBBB
          XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBB BBBBBBBBBBXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXX
                    BB BBB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBB BB BXXXXXXXXBBBBB
                    XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
              BB BBB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBB BB B gettext(u'Table is full') BBBB gettext(u'Join this table') BBBBB
            XXXXXXXXX
          XXXXXXX
        BBBBB
      BBBB
        XX XXXXXXBBB BBBBBBBXXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBX
           XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Login to join table') 
        XXXX
      BBBBB
    BBBB
      XXXXXXX XXXXXXXX
              XXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'This table is closed') 
      XXXXXXXXX
    BBBBB
  XXXXXX

BBBBBBBB BBBBBBB


BBBBB BBBBBBBBBBB
  XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  BB BBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXX XXXXXXXXXXX            X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX        X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXX   X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXX     X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX       X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX

        XXXXXXXX XXXXXXXXXXXXXXXXXXX X
          XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
          XXX
        X

        XXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXX X
          XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXX
          XXXXXX XXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
              XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXX X
                XXXXXXXXXXXXXXXXX X X X XX
                XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
              X
            XXX
            XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          X
        XXX

        XX XXXXXXXXXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX X
            XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX
        X

        XX XXXXXXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XX
              XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X X X
            XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
              XXXXXXX XXXXXXX
              XXXXXXXX X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX XX
              XXXXX XXXXXXXXXXXXXXXX XXXXXXX XX
            XXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XX X
              XX XXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Leaderboard Updated') XX
                XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              X
            XXX
          XXX
        X

        XX XXXXXXXXXXXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX
        X
      XXX
    XXXXXXXXX
  BBBBB
BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFXXXXXXXXX
BBBBBBBB
