BBBBBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB
  
  XXXXXXX
    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXXXXXXX XXXX XXXXXXXXXXX
      XXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXX XXXXXXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXX XXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXXX X XXX XXX XXXX XXXXX X X X XXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    X
  XXXXXXXX
BBBBBBBB

BBBBB BBBBBBB

  XXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
    XXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Manage players') XXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX

    
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Players') XXXX
        BB BBBBBBBBBBBB BB BBBBBBBBBBBB
          XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXX X X XXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXXXXXX XXXX X X X XXXX XXXXXX XX
            XXXXXX
             gettext(u'Closed') 
          XXXXXXX
        BBBBB
      XXXXXX

      BB BBBBBBB
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          BBB BBBBBB BB BBBBBBB
            XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXX XXXXXX
              BB BBBBBBBBBBBBBBB
                XXXX XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXX
                  XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'guest of')  XXXXXXX
                XXXXXX
              BBBB
                XXXX XXXXXX XXXXXX
                     XXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              BBBBB
              XXXXXXX XXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBX
                      XXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX XXX XXXX XXX XX
                XXXXXX
              XXXXXXXXX
            XXXXX
          BBBBBB
        XXXXX
      BBBB
        XX XXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'No players yet.') XXXX
      BBBBB
    XXXXXX

    
    BB BBBBBBBBBBBBBBB B B BB BBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Invite a gamer') XXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXX XXXXXXXXXXXXXXXXX XXXXX X X X XXXXX XXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX
            XXXXXX
             gettext(u'Add') 
          XXXXXXXXX
        XXXXXXX
      XXXXXX
    BBBB
      XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX X X X XXXXXXXXXX X X X X XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X X X XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X X XXXXXXXXX XXXXXXX XXXXX X X XXXXXXXXXXXXXX XXXXXXX XXXXX X X X XX XXXXXXXXXXX XXXXX X X XXXXXXX XXXXXXX XXX X X X XXXXXXX XXXX XXXXX XXXXX X X X XXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXX XXXXXXXX XXXXXX X X X XXX X X X X X X X XXXX XXXXXX XXXX X X XXXXX X XXXX XXXX X X X XXX XXXXXXXX XXXXXX XXXX X X XXXXX X XXXX XXXX X X X XXX XXX XX
        XXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Table is full') XXXX
      XXXXXX
    BBBBB

    
    XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX
      XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'External players') XXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
        XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
          XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBB BB BXXXXXXXXBBBBB
                    XXXXXXXXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XX
              XXXXXX
            XXXXXXXXX
          XXXXXXX
          XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBB BB B BBB BBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
                    XXXXXXXXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XX
              XXXXXX
            XXXXXXXXX
          XXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBB B B
            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX
              BBBBBBBBBB
              XXXXXXX XXXXXXXXXXXXX
                      XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                 gettext(u'Clear') 
              XXXXXXXXX
            XXXXXXX
          BBBBB
        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX

  
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXX XXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Remove player?') XXXX
      XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX gettext(u'Are you sure you want to remove')  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
           gettext(u'Cancel') 
        XXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          BBBBBBBBBB
          XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Remove') 
          XXXXXXXXX
        XXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

BBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
  XXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
    XXX

    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
      XXX
    XXX
  XXXXXXXXX
BBBBBBBB
