BBBB BBBB

XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBX
   XXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

  
  XXXX XXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBB BBB BBBBBBBBBBBBBBBB
      XXXX XXXXXX XXXXXX
           XXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    BBBB
      XXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXX XXXX XXXXX XXXXXXXXX X XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXX X X XXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX X X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX X XXXXXXX XXXX XXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX X X X XXXXXXXXX XXXXX XXXXX X X X XXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X X XXXXXXXXX XXXXXX XXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXX XX
        XXXXXX
      XXXXXX
    BBBBB
  XXXXXX

  
  XXXX XXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
      XXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
        BB BBBBBBBBBBBBBBB BBBBBBBBBBBBBB gettext(u'Game TBD') BBBBB
      XXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX
                   BB BBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXX XXXXXXXXXXXXXX
                   BBBB BBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                   BBBBXXXXXXXXXXXX XXXXXXXXXXXXXXBBBBBXX
        
      XXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXX
      
      XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXX X X X XXXX X X X X X X XX XXX XX
        XXXXXX
        FFFFFFFFFFXFFFFFFFFFF
      XXXXXXX
      
      BB BBBBBBBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXX X X X X XXXXXXXXXXX XXX X X X XXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XX
          XXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
      BBBB BBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXX X X X X XXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX X X X X XXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X XXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXXXX XXXXXX XXXX X X X XXXXXXXXXXXXXXXXX XXXX X X X XXXXX XXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXX XX
          XXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
      BBBBB
      
      XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXX X X X XXXXXXXXX XXXXX XXXXX X X X XXXXXXXXXX XXXXX XXXXX X X XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX X X X XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X X X XXXXXXXXXXXXXX XXXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXXXXXX XXXXXXXXXX XXXXX X X XXXXXX X XXXXX XXXXX X X X XXXX XXX XX
        XXXXXX
        XBB BBBBBBBBBBBBBBBBBBBBBXBBBBBBBBB
      XXXXXXX
      
      BB BBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      BBBBB
      
      BB BBBBBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX
          XXXXXX
           gettext(u'Conflict') 
        XXXXXXX
      BBBBB
    XXXXXX
  XXXXXX
XXXX
