BBBB BBBB

XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX
   XXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX

  
  XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXX XXXXXX
         XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    BB BBBBB BBB BBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBB BB BBBBB
      XXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
         gettext(u'Event') 
      XXXXXXX
    BBBB
      XXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
         gettext(u'Past') 
      XXXXXXX
    BBBBB
    BB BBBBBBBBBB
      XXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXXX XXXXXXXXXXXX XXXXX XXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X X X XXX X X X X X X X XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XXX XXXXXXXX XXX X X X XX XXX XXXXXXXX
        
      XXXXXXX
    BBBBB
  XXXXXX

  
  XXXX XXXXXXXXXX XXXXXX XXXX XXXXXXXX XXXXXXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBB
      XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX X X X XXXXXXXXXXXXXXXXXXX XXXX X X X XX XXXXXXXXXXXXX XXXXXX XXXX X X X XXXX XXXXXXXXXXXX XXXX X X X XX XXXXXXXXX XXXXXXXXXXX XXXX X X X XXXX XXXXXXXXXXX XXXX X X X XX XXXXXX XXXXXXXX
        BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
          FFFFFFF F FF
        BBBB
          FFFFFFF FF X FFFFFFF F FF
        BBBBB
      XXXXXXX
    BBBBB
  XXXXXX

XXXX
