BBBB BBBB

 gettext(u'Hey')  X
 gettext(u'A new table has been created by %(creator_name)s at %(location_name)s.') S SSS SSSSS SSS SSSS SSSSSSS SS SSSSSSSSSSSSSSSS SS SSSSSSSSSSSSSSSSSS

 gettext(u'Game:')  BBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBB gettext(u'Not decided yet') BBBBBBBBXXXXXXXBBBBBBBBBBB
 gettext(u'Date and time:')  X BBBBBBBBXXXXX XXXXXXXXXXXXXXXXXX
BBBBBBBBBBB gettext(u'Description:')  BBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBB


XXXXXXXXXXXXXXXX
