BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBB
   gettext(u'New message from contact form') 
BBBBBBBB BBBBB

BBBBB BBBBBBBBBBBB
    XXXXXXXX gettext(u'name') XXXXXXXXXXXXX
    XXXXXXXX

    XXXXXXXX gettext(u'email') XXXXXXXXXXXXX
    XXXXXXXX

    XXXXXXXX gettext(u'message') XXXXXXXXXXXXX
    
BBBBBBBB BBBBBBBBBBBB
