BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBB
   gettext(u'New Table') 
BBBBBBBB BBBBB

BBBBB BBBBBBBBBBBB
   gettext(u'Hey')  XXXXX
   gettext(u'A new table has been created by <strong>%(creator_name)s</strong> at <strong>%(location_name)s</strong>.') S SSS SSSSS SSS SSSS SSSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXXXXXXX

  XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX
      XXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXX gettext(u'Title:') XXXXXXXXX XXXX
        XXXXXXXX gettext(u'Game:') XXXXXXXXX BBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBB gettext(u'Not decided yet') BBBBBBBBXXXXXXXBBBBBBBBBBBXXXX
        XXXXXXXX gettext(u'Date and time:') XXXXXXXXX X BBBBBBBBXXXXX XXXXXXXXXXXXXBBBBBBBBBBBXXXX
        XXXXXXXX gettext(u'Description:') XXXXXXXXX BBBBBBBBXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBB
      XXXXX
    XXXXX
  XXXXXXXX
BBBBBBBB BBBBBBBBBBBB

BBBBB BBBBBBBBB
   gettext(u'See table') 
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBBB
  
BBBBBBBB BBBBBBBB
