BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBB
   gettext(u'New player') 
BBBBBBBB BBBBB

BBBBB BBBBBBBBBBBB
   gettext(u'Hey')  XXXXX
   gettext(u'A new player joined the table')  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

  BB BBBB
  XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX
      XXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXX gettext(u'Game:') XXXXXXXXX 
      XXXXX
    XXXXX
  XXXXXXXX
  BBBBB
BBBBBBBB BBBBBBBBBBBB

BBBBB BBBBBBBBB
   gettext(u'See table') 
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBBB
  
BBBBBBBB BBBBBBBB
