BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBB
   gettext(u'New Messages') 
BBBBBBBB BBBBB

BBBBB BBBBBBBBBBBB
  XXX gettext(u'Hi')  XXXXX
  XXX gettext(u'You have')  XXXXXXXXXXXXXXXXX  gettext(u'new unread messages in the following tables:') XXXX

  XXXX

    BBB BBBBBB BB BBBBBBBBBBBBB
      XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX
            X  gettext(u'new messages')  X
            XX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Link to table') 
            XXXXX
          XXXXX
        XXXXX
      XXXXXXXX
    BBBBBB
BBBBBBBB BBBBBBBBBBBB
