BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBB

BBBBB BBBBB
   gettext(u'Table deleted') 
BBBBBBBB BBBBB

BBBBB BBBBBBBBBBBB
   gettext(u'Hey')  XXXXX
   gettext(u'We are sorry to inform you that a table you were participating in has been deleted.') XXXXXXXXX

  XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX
      XXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXX gettext(u'Title:') XXXXXXXXX XXXX
        XXXXXXXX gettext(u'Game:') XXXXXXXXX BB BBBBBBBB gettext(u'Not decided yet') BBBBBXXXX
        XXXXXXXX gettext(u'Date and time:') XXXXXXXXX X XXXX
        XXXXXXXX gettext(u'Location:') XXXXXXXXX 
      XXXXX
    XXXXX
  XXXXXXXX
BBBBBBBB BBBBBBBBBBBB

BBBBB BBBBBBBBB
   gettext(u'Check other tables') 
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBBB
  
BBBBBBBB BBBBBBBB
