# Generated by Django 5.0 on 2024-02-24 09:27

import django.db.models.deletion
import webapp.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=webapp.storage_backends.PublicMediaStorage(), upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='table',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='webapp.location'),
        ),
    ]
