# Generated by Django 5.0.2 on 2025-03-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_table_game_alter_table_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='games',
        ),
    ]
