# Generated by Django 5.0.2 on 2025-03-17 14:17

import webapp.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_table_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=webapp.storage_backends.PublicMediaStorage(), upload_to='games'),
        ),
    ]
