# Generated by Django 5.0 on 2024-02-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_userprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='location-covers/'),
        ),
    ]
