# Generated by Django 5.0 on 2024-02-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
