# Generated by Django 5.0 on 2024-02-27 14:30

import webapp.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_location_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=webapp.storage_backends.PublicMediaStorage(), upload_to='location-covers'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=webapp.storage_backends.PublicMediaStorage(), upload_to='avatars'),
        ),
    ]
