# Generated by Django 5.0 on 2024-02-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_location_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='content',
            new_name='description',
        ),
    ]
