# Generated by Django 5.0 on 2024-02-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_content_table_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='min_players',
            field=models.SmallIntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='table',
            name='max_players',
            field=models.SmallIntegerField(blank=True, default=5),
        ),
    ]
