# Generated by Django 5.0.2 on 2025-03-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
