# Generated by Django 5.0.2 on 2024-02-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_location_point_userprofile_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='point',
        ),
    ]
