# Generated by Django 5.0 on 2024-02-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_table_min_players_alter_table_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_public_location',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
