# Generated by Django 5.0.2 on 2024-04-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_table_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
