# Generated by Django 5.0.2 on 2025-03-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='leaderboard_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
