# Generated by Django 5.0.2 on 2025-03-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_game_leaderboard_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='leaderboard_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
