# Generated by Django 5.0 on 2024-02-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_location_address_alter_location_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_private',
        ),
        migrations.AddField(
            model_name='location',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
