# Generated by Django 5.0.2 on 2025-03-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_game_leaderboard_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='leaderboard_status',
            field=models.CharField(choices=[('not_editable', 'Not Editable'), ('editable', 'Editable')], default='editable', max_length=20),
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('ongoing', 'On Going'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
