# Generated by Django 5.0.2 on 2025-04-03 17:09

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_table_leaderboard_status_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='table',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tables', to='webapp.game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='table',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='webapp.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='table',
            name='max_players',
            field=models.SmallIntegerField(blank=True, default=5, verbose_name='Maximum players'),
        ),
        migrations.AlterField(
            model_name='table',
            name='min_players',
            field=models.SmallIntegerField(blank=True, default=2, verbose_name='Minimum players'),
        ),
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Hour'),
        ),
        migrations.AlterField(
            model_name='table',
            name='title',
            field=models.CharField(blank=True, max_length=144, verbose_name='Title'),
        ),
    ]
