# Generated by Django 5.0.2 on 2025-04-04 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_table_date_alter_table_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_leaderboard_reminder',
            field=models.BooleanField(default=True, verbose_name='Notification Leaderboard Reminder'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_leaderboard_update',
            field=models.BooleanField(default=True, verbose_name='Notification Leaderboard Update'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_new_player',
            field=models.BooleanField(default=True, verbose_name='Notification New Player'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_new_table',
            field=models.BooleanField(default=True, verbose_name='Notification New Table'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('new_table', 'New table created'), ('new_player', 'New player joined'), ('leaderboard_reminder', 'Create leaderboard'), ('leaderboard_update', 'Leaderboard updated')], max_length=50)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.location')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='webapp.userprofile')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.table')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='webapp.location')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_locations', to='webapp.userprofile')),
            ],
            options={
                'verbose_name': 'Location Follower',
                'verbose_name_plural': 'Location Followers',
                'unique_together': {('user_profile', 'location')},
            },
        ),
    ]
