# Generated by Django 5.0.2 on 2025-04-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_notification_location_alter_notification_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_table', 'New table created'), ('new_player', 'New player joined'), ('leaderboard_reminder', 'Create leaderboard'), ('leaderboard_update', 'Leaderboard updated'), ('new_comment', 'New comment')], max_length=50),
        ),
    ]
