# Generated by Django 5.0.2 on 2025-04-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_new_comments',
            field=models.BooleanField(default=True, verbose_name='Notification New Comments'),
        ),
    ]
