# Generated by Django 5.0.2 on 2025-04-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_userprofile_notification_new_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_table', 'New table created'), ('new_player', 'New player joined'), ('leaderboard_reminder', 'Leaderboard is now editable'), ('leaderboard_update', 'Leaderboard closed'), ('table_closed', 'Table closed'), ('new_comment', 'New comment')], max_length=50),
        ),
    ]
