# Generated by Django 5.0.2 on 2025-10-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_table', 'New table created'), ('new_player', 'New player joined'), ('leaderboard_editable', 'Leaderboard is now editable'), ('leaderboard_updated', 'Leaderboard updated'), ('leaderboard_closed', 'Leaderboard closed'), ('table_closed', 'Table closed'), ('table_deleted', 'Table deleted'), ('new_comment', 'New comment')], max_length=50),
        ),
    ]
