# Generated by Django 5.0.2 on 2025-11-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italiano')], default='it', max_length=7),
        ),
    ]
