# Generated by Django 5.0.2 on 2026-01-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_userprofile_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_locations', to='webapp.userprofile'),
        ),
    ]
