# Generated by Django 6.0.2 on 2026-02-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_comment_comment_type_alter_comment_author'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set(),
        ),
    ]
