# Generated by Django 5.0.2 on 2026-01-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_comment_comment_type_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='external_players',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
