# Generated by Django 6.0.2 on 2026-03-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_member_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='enable_membership',
            field=models.BooleanField(default=False),
        ),
    ]
