# Generated by Django 6.0.2 on 2026-03-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_location_enable_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='leaderboard_status',
            field=models.CharField(choices=[('not_editable', 'Not Editable'), ('editable', 'Editable')], default='not_editable', max_length=20),
        ),
    ]
