# Generated by Django 6.0.2 on 2026-03-10 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_add_uuid_to_member_membership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='player',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.userprofile'),
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_profiles', to='webapp.userprofile', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Guest Profile',
                'verbose_name_plural': 'Guest Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='guest_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_players', to='webapp.guestprofile'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(condition=models.Q(('user_profile__isnull', False)), fields=('user_profile', 'table'), name='unique_user_profile_table'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_profile__isnull', False)), fields=('guest_profile', 'table'), name='unique_guest_profile_table'),
        ),
    ]
