# Generated by Django 6.0.2 on 2026-03-15 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_guest_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('ownership', models.CharField(choices=[('location', 'Location'), ('member', 'Member')], default='location', max_length=20, verbose_name='Ownership')),
                ('physical_location', models.CharField(choices=[('association', 'At the association'), ('home', "At member's home")], default='association', max_length=20, verbose_name='Physical Location')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_games', to='webapp.game', verbose_name='Game')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_games', to='webapp.location', verbose_name='Location')),
                ('owner_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_games', to='webapp.member', verbose_name='Owner Member')),
            ],
            options={
                'verbose_name': 'Location Game',
                'verbose_name_plural': 'Location Games',
                'ordering': ['game__name'],
                'unique_together': {('location', 'game')},
            },
        ),
    ]
