# Generated by Django 6.0.2 on 2026-03-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_location_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationgame',
            name='ownership',
            field=models.CharField(choices=[('location', 'Owned by Location'), ('member', 'Owner by Member')], default='location', max_length=20, verbose_name='Ownership'),
        ),
    ]
