# Generated by Django 6.0.2 on 2026-03-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_alter_locationgame_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bgg_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='BGG Code'),
        ),
    ]
