# Generated by Django 6.0.2 on 2026-03-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_add_bgg_code_to_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Maximum players'),
        ),
        migrations.AddField(
            model_name='game',
            name='max_playtime',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Max playtime (minutes)'),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Minimum players'),
        ),
        migrations.AddField(
            model_name='game',
            name='min_playtime',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Min playtime (minutes)'),
        ),
        migrations.AddField(
            model_name='game',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Weight'),
        ),
    ]
