# Generated by Django 6.0.2 on 2026-03-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_add_game_bgg_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='year_published',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Year published'),
        ),
    ]
