# Generated by Django 6.0.2 on 2026-03-17 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_faq_modeltranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_it', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category__order', 'order'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        # Drop NOT NULL constraint and clear legacy string values before converting to FK
        migrations.RunSQL(
            "ALTER TABLE webapp_faq ALTER COLUMN category DROP NOT NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL("UPDATE webapp_faq SET category = NULL"),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='webapp.faqcategory', verbose_name='Category'),
        ),
    ]
