# Generated by Django 6.0.2 on 2026-03-18 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_faq_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Chat ID')),
                ('chat_title', models.CharField(blank=True, max_length=255, verbose_name='Chat title')),
                ('label', models.CharField(blank=True, max_length=64, verbose_name='Label')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_configs', to='webapp.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Telegram Group Config',
                'verbose_name_plural': 'Telegram Group Configs',
            },
        ),
        migrations.CreateModel(
            name='TelegramSetupToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('used', models.BooleanField(default=False, verbose_name='Used')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_tokens', to='webapp.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Telegram Setup Token',
                'verbose_name_plural': 'Telegram Setup Tokens',
            },
        ),
    ]
