# Generated by Django 6.0.2 on 2026-03-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_telegram_group_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroupconfig',
            name='label',
        ),
    ]
