# Generated by Django 6.0.2 on 2026-03-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_remove_label_from_telegram_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_full_name',
            field=models.BooleanField(default=False, verbose_name='Show full name on profile'),
        ),
    ]
