# Generated by Django 6.0.2 on 2026-03-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_add_show_full_name_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='enable_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
