# Generated by Django 6.0.2 on 2026-03-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_add_location_enable_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='show_tables_in_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
