# Generated by Django 6.0.2 on 2026-03-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_add_location_show_tables_in_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroupconfig',
            name='message_thread_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Message thread ID'),
        ),
    ]
