# Generated by Django 6.0.2 on 2026-03-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_telegram_group_config_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroupconfig',
            name='message_thread_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Message thread title'),
        ),
    ]
