# Generated by Django 6.0.2 on 2026-03-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0046_location_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bgg_imported',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
