# Generated by Django 6.0.2 on 2026-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0047_add_bgg_imported_and_verified_to_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='table_creation_permission',
            field=models.CharField(choices=[('anyone', 'Anyone'), ('members_only', 'Members only'), ('managers_only', 'Owners and managers only')], default='anyone', max_length=20, verbose_name='Who can create tables'),
        ),
        migrations.AddField(
            model_name='location',
            name='table_join_permission',
            field=models.CharField(choices=[('anyone', 'Anyone'), ('members_only', 'Members only')], default='anyone', max_length=20, verbose_name='Who can join tables'),
        ),
    ]
