# Generated by Django 6.0.2 on 2026-04-02 14:59

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
import meta.models
import webapp.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0048_add_location_permission_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=144, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover', models.ImageField(blank=True, null=True, storage=webapp.storage_backends.PublicMediaStorage(), upload_to='event-covers', verbose_name='Cover')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=144, null=True, verbose_name='City')),
                ('latitude', models.CharField(blank=True, max_length=25, null=True)),
                ('longitude', models.CharField(blank=True, max_length=25, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('allowed_table_creators', models.ManyToManyField(blank=True, related_name='event_table_creation_allowed', to='webapp.userprofile', verbose_name='Additional table creators')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='webapp.userprofile', verbose_name='Creator')),
                ('managers', models.ManyToManyField(blank=True, related_name='managed_events', to='webapp.userprofile', verbose_name='Managers')),
                ('sponsor_locations', models.ManyToManyField(blank=True, related_name='sponsored_events', to='webapp.location', verbose_name='Sponsor locations')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.AddField(
            model_name='table',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='webapp.event', verbose_name='Event'),
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='webapp.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event Date',
                'verbose_name_plural': 'Event Dates',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PlayArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=144, verbose_name='Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_areas', to='webapp.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Play Area',
                'verbose_name_plural': 'Play Areas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='table',
            name='play_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='webapp.playarea', verbose_name='Play Area'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', True), ('location__isnull', False)), models.Q(('event__isnull', False), ('location__isnull', True)), _connector='OR'), name='table_location_xor_event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventdate',
            unique_together={('event', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='playarea',
            unique_together={('event', 'name')},
        ),
    ]
