# Generated by Django 6.0.2 on 2026-04-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0049_event_table_event_eventdate_playarea_table_play_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
