# Generated by Django 6.0.2 on 2026-04-13 15:43

from django.db import migrations, models


def reset_notification_new_player(apps, schema_editor):
    UserProfile = apps.get_model('webapp', 'UserProfile')
    UserProfile.objects.all().update(notification_new_player=False)


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0050_change_location_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification_new_player',
            field=models.BooleanField(default=False, verbose_name='Notification New Player'),
        ),
        migrations.RunPython(reset_notification_new_player, migrations.RunPython.noop),
    ]
