# Generated by Django 6.0.2 on 2026-04-13 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0051_notification_new_player_default_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(20, 30), verbose_name='Hour'),
        ),
    ]
