# Generated by Django 6.0.2 on 2026-04-16 16:29

from django.db import migrations
from django.utils import timezone


def mark_existing_notifications_push_sent(apps, schema_editor):
    Notification = apps.get_model('webapp', 'Notification')
    Notification.objects.filter(push_sent=False).update(
        push_sent=True,
        push_sent_at=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0053_pwa_push_notifications'),
    ]

    operations = [
        migrations.RunPython(
            mark_existing_notifications_push_sent,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
