# Generated by Django 6.0.2 on 2026-06-14 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0054_mark_existing_notifications_push_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=120, help_text='Expected duration in minutes', verbose_name='Duration (minutes)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone'),
        ),
        migrations.CreateModel(
            name='PhysicalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(help_text='On-site label, e.g. "Table 1"', max_length=144, verbose_name='Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_tables', to='webapp.event', verbose_name='Event')),
                ('play_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_tables', to='webapp.playarea', verbose_name='Play Area')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'ordering': ['order', 'name'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.AddField(
            model_name='table',
            name='physical_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='webapp.physicaltable', verbose_name='Station'),
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='webapp.event', verbose_name='Event')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='webapp.userprofile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Event Participant',
                'verbose_name_plural': 'Event Participants',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'user_profile')},
            },
        ),
    ]
