# Generated by Django 6.0.6 on 2026-07-03 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0055_table_duration_userprofile_phone_physicaltable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='default_table_time',
            field=models.TimeField(blank=True, default=datetime.time(20, 30), help_text='Default start time used when creating new tables at this location.', verbose_name='Default table time'),
        ),
    ]
