# Generated by Django 6.0.6 on 2026-07-08 15:23

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0056_location_default_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IT', verbose_name='Phone'),
        ),
    ]
