# Generated by Django 6.0.6 on 2026-07-08 16:35

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0058_normalize_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IT', verbose_name='Phone'),
        ),
    ]
