# Generated by Django 6.0.6 on 2026-07-09 08:59

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0060_normalize_event_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='IT', verbose_name='Phone Number'),
        ),
    ]
