# Generated by Django 6.0.6 on 2026-07-14 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0062_normalize_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Label')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='webapp.table', verbose_name='Table')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
