# Generated by Django 6.0.6 on 2026-07-15 09:34

import webapp.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0063_tablelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='custom_cover',
            field=models.ImageField(blank=True, help_text='Optional image shown instead of the game cover.', null=True, storage=webapp.storage_backends.PublicMediaStorage(), upload_to='table-covers', verbose_name='Custom cover'),
        ),
    ]
