# Generated by Django 6.0.6 on 2026-07-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0064_table_custom_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='webapp.event', verbose_name='Event'),
        ),
    ]
