# Generated by Django 6.0.6 on 2026-08-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0065_alter_table_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=144, verbose_name='Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_categories', to='webapp.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event Table Category',
                'verbose_name_plural': 'Event Table Categories',
                'ordering': ['order', 'name'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.AddField(
            model_name='table',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='webapp.eventtablecategory', verbose_name='Category'),
        ),
    ]
