# Generated by Django 6.0.6 on 2026-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0066_eventtablecategory_table_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='unlimited_seats',
            field=models.BooleanField(blank=True, default=False, help_text='No seat limit: anyone can join and no empty seats are shown.', verbose_name='Unlimited seats'),
        ),
    ]
