# Generated by Django 6.0.6 on 2026-09-08 14:02

import django.core.validators
import re
from django.db import migrations, models


def normalize_fiscal_code(apps, schema_editor):
    """
    `code` was a free-text member code up to 50 characters; `fiscal_code` is
    capped at 16, so anything longer would break the column alteration.
    Normalize what fits and clear what cannot be a fiscal code.
    """
    Member = apps.get_model('webapp', 'Member')
    for member in Member.objects.exclude(fiscal_code='').only('id', 'fiscal_code').iterator():
        normalized = member.fiscal_code.strip().upper()
        member.fiscal_code = normalized if len(normalized) <= 16 else ''
        member.save(update_fields=['fiscal_code'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0067_table_unlimited_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='code',
            new_name='fiscal_code',
        ),
        migrations.RunPython(normalize_fiscal_code, noop),
        migrations.AlterField(
            model_name='member',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Enter a valid fiscal code (16 characters), or leave the field empty.', regex='^[A-Z]{6}[0-9A-Z]{2}[A-Z][0-9A-Z]{2}[A-Z][0-9A-Z]{3}[A-Z]$')], verbose_name='Fiscal Code'),
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='member',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Place of Birth'),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='member',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='member',
            name='province',
            field=models.CharField(blank=True, max_length=2, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='member',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='ZIP Code'),
        ),
    ]
