# Generated by Django 6.0.6 on 2026-09-08 14:55

import django.db.models.deletion
import uuid
import webapp.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0068_member_fiscal_code_and_personal_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('file', models.FileField(storage=webapp.storage_backends.PublicMediaStorage(), upload_to='membership-documents', verbose_name='File')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_documents', to='webapp.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Membership Document',
                'verbose_name_plural': 'Membership Documents',
                'ordering': ['name'],
            },
        ),
    ]
