# Generated by Django 6.0.6 on 2026-09-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0069_membershipdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='signed_document',
            field=models.BooleanField(default=False, verbose_name='Signed document received'),
        ),
    ]
