# Generated by Django 6.0.6 on 2026-10-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0070_membership_signed_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdate',
            name='closing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Closing time'),
        ),
        migrations.AddField(
            model_name='eventdate',
            name='opening_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Opening time'),
        ),
    ]
